/* Generated by Together */

package org.alt60m.security.dbio.manager;

public class SecurityManagerException extends Exception {
    public SecurityManagerException() {
        super();
    }

    public SecurityManagerException(String message) {
        super(message);
    }
    
    public SecurityManagerException(String message, Throwable t) {
        super(message, t);
    }
}
