/* Generated by Together */

package org.alt60m.security.dbio.manager;

/** This exception is thrown when condition occurred */
public class UserNotFoundException extends SecurityManagerException {
	/** Constructs an Exception without a message. */
	public UserNotFoundException() {
		super();
	}

	/**
	 * Constructs an Exception with a detailed message.
	 * @param Message The message associated with the exception.
	 */
	public UserNotFoundException(String message) {
		super(message);
	}
	
    public UserNotFoundException(String message, Throwable t) {
        super(message, t);
    }
}
