/* Generated by Together */

package org.alt60m.security.dbio.manager;

/** This exception is thrown when condition occurred */
public class UserAlreadyExistsException extends SecurityManagerException {
	/** Constructs an Exception without a message. */
	public UserAlreadyExistsException() {
		super();
	}

	/**
	 * Constructs an Exception with a detailed message.
	 * @param Message The message associated with the exception.
	 */
	public UserAlreadyExistsException(String message) {
		super(message);
	}
}
