/* Generated by Together */

package org.alt60m.hr.review360.model;

import java.util.Date;
import java.util.Calendar;

/**
 * @persistent 
 * @table hr_review360_review360light
 * @cache-type none
 * @access shared
 * @key-generator UUID
 */
public class Review360Light {
	/**
     * @field-type org.alt60m.hr.review360.model.ReviewSessionLight
     * @sql-type varchar
     * @sql-size 64
     * @sql-name fk_ReviewSessionID
     * @sql-index
     * @set-method assocReviewSession
     * @get-method getReviewSession
     */
    private ReviewSessionLight session;

	/**
     * @sql-type varchar
     * @sql-size 64
     * @primary-key
     */
    private String Review360LightID = "";

	/**
     * @sql-type varchar
     * @sql-size 64
     */
	private String reviewedByID = "";
	private Date dateStarted = null;
	private Date dateCompleted = null;
	private Date dateDue = null;

	/**
     * @sql-type varchar
     * @sql-size 128
     */
	private String currentPosition = "";
	/**
     * @sql-type varchar
     * @sql-size 128
     */
	private String leadershipLevel = "";
	private String relationship = "";
	private String q1 = "";
	private String q2;
	private String q3 = "";
	private String q4 = "";
	private String q5 = "";
	private String q6 = "";
	private String q7 = "";
	private String q8;
	private String q9 = "";


    public String getReview360LightID() {
		return Review360LightID;
    }

	public void setReview360LightID(String Review360LightID) {
		this.Review360LightID = Review360LightID;
	}
	public String getReviewedByID() {
		return reviewedByID; 
	}
	public void setReviewedByID(String reviewedByID) {
		this.reviewedByID = reviewedByID; 
	}
	public Date getDateStarted() {
		return dateStarted; 
	}
	public void setDateStarted(Date dateStarted) {
	    if (dateStarted != null) {
		Calendar cin = Calendar.getInstance();
		Calendar cout = Calendar.getInstance();
		cin.setTime(dateStarted);
		cout.clear();
		cout.set(cin.get(Calendar.YEAR), cin.get(Calendar.MONTH), cin.get(Calendar.DATE));
		this.dateStarted = cout.getTime();
	    } else {
		this.dateStarted = dateStarted;
	    }	    
	}
	public Date getDateCompleted() {
		return dateCompleted; 
	}
	public void setDateCompleted(Date dateCompleted) {
	    if (dateCompleted != null) {
		Calendar cin = Calendar.getInstance();
		Calendar cout = Calendar.getInstance();
		cin.setTime(dateCompleted);
		cout.clear();
		cout.set(cin.get(Calendar.YEAR), cin.get(Calendar.MONTH), cin.get(Calendar.DATE));
		this.dateCompleted = cout.getTime();
	    } else {
		this.dateCompleted = dateCompleted;
	    }	    
	}
	public Date getDateDue() {
		return dateDue; 
	}
	public void setDateDue(Date dateDue) {
	    if (dateDue != null) {
		Calendar cin = Calendar.getInstance();
		Calendar cout = Calendar.getInstance();
		cin.setTime(dateDue);
		cout.clear();
		cout.set(cin.get(Calendar.YEAR), cin.get(Calendar.MONTH), cin.get(Calendar.DATE));
		this.dateDue = cout.getTime();
	    } else {
		this.dateDue = dateDue;
	    }	    
	}
	public String getCurrentPosition() {
		return currentPosition; 
	}
	public void setCurrentPosition(String currentPosition) {
		this.currentPosition = currentPosition; 
	}
	public String getLeadershipLevel() {
		return leadershipLevel; 
	}
	public void setLeadershipLevel(String leadershipLevel) {
		this.leadershipLevel = leadershipLevel; 
	}
	public String getRelationship() {
		return relationship; 
	}
	public void setRelationship(String relationship) {
		this.relationship = relationship; 
	}
	public String getQ1() {
		return q1; 
	}
	public void setQ1(String q1) {
		this.q1 = q1; 
	}
	public String getQ2() {
		return q2;
	}
	public void setQ2(String q2) {
		this.q2 = q2;
	}
	public String getQ3() {
		return q3; 
	}
	public void setQ3(String q3) {
		this.q3 = q3; 
	}
	public String getQ4() {
		return q4; 
	}
	public void setQ4(String q4) {
		this.q4 = q4; 
	}
	public String getQ5() {
		return q5; 
	}
	public void setQ5(String q5) {
		this.q5 = q5; 
	}
	public String getQ6() {
		return q6; 
	}
	public void setQ6(String q6) {
		this.q6 = q6; 
	}
	public String getQ7() {
		return q7; 
	}
	public void setQ7(String q7) {
		this.q7 = q7; 
	}
	public String getQ8() {
		return q8;
	}
	public void setQ8(String q8) {
		this.q8 = q8;
	}
	public String getQ9() {
		return q9; 
	}
	public void setQ9(String q9) {
		this.q9 = q9; 
	}

    public ReviewSessionLight getReviewSessionLight(){
            return session;
        }

    public void dissocReviewSessionLight(){
		this.session = null;
    }
	public void assocReviewSessionLight(ReviewSessionLight session){
		this.session = session;
    }

}
