/* Generated by Together */

package org.alt60m.hr.review360.model;

import java.util.HashSet;
import java.util.Date;
import java.util.Set;
import java.util.Calendar;

/**
 * @persistent 
 * @table hr_review360_reviewsessionlight
 * @cache-type none
 * @access shared
 * @key-generator UUID
 */
public class ReviewSessionLight {

	/**
     * @sql-type varchar
     * @sql-size 64
     * @primary-key
     */
    private String ReviewSessionLightID = "";
	/**
     * @sql-type varchar
     * @sql-size 80
     */
    private String name = "";
	/**
     * @sql-type varchar
     * @sql-size 255
     */
	private String purpose = "";


	private Date dateDue = null;
	private Date dateStarted = null;
	/**
     * @sql-type varchar
     * @sql-size 128
     */
    private String revieweeID = "";
		/**
     * @sql-type varchar
     * @sql-size 128
     */
    private String administratorID = "";
		/**
     * @sql-type varchar
     * @sql-size 128
     */
    private String requestedByID = "";

    /** @associates <{Review360}>
     * @clientCardinality 1
     * @supplierCardinality 0..*
     * @undirected
     * @label theReviews
     * 
     * @field-type org.alt60m.hr.review360.model.Review360Light
     * @many-key fk_ReviewSessionID
     * @get-method getReview360Lights
     * @set-method setReview360Lights
     */
    private Set reviews = new HashSet();

	public String getReviewSessionLightID() {
		return ReviewSessionLightID;
	}
	public void setReviewSessionLightID(String ReviewSessionLightID) {
		this.ReviewSessionLightID = ReviewSessionLightID;
	}
	public String getName() {
		return name; 
	}
	public void setName(String name) {
		this.name = name; 
	}
	public String getPurpose() {
		return purpose; 
	}
	public void setPurpose(String purpose) {
		this.purpose = purpose; 
	}
	public Date getDateDue() {
		return dateDue; 
	}
	public void setDateDue(Date dateDue) {
	    if (dateDue != null) {
		Calendar cin = Calendar.getInstance();
		Calendar cout = Calendar.getInstance();
		cin.setTime(dateDue);
		cout.clear();
		cout.set(cin.get(Calendar.YEAR), cin.get(Calendar.MONTH), cin.get(Calendar.DATE));
		this.dateDue = cout.getTime();
	    } else {
		this.dateDue = dateDue;
	    }	    
	}
	public Date getDateStarted() {
		return dateStarted; 
	}
	public void setDateStarted(Date dateStarted) {
	    if (dateStarted != null) {
		Calendar cin = Calendar.getInstance();
		Calendar cout = Calendar.getInstance();
		cin.setTime(dateStarted);
		cout.clear();
		cout.set(cin.get(Calendar.YEAR), cin.get(Calendar.MONTH), cin.get(Calendar.DATE));
		this.dateStarted = cout.getTime();
	    } else {
		this.dateStarted = dateStarted;
	    }	    
	}
	public String getRevieweeID() {
		return revieweeID; 
	}
	public void setRevieweeID(String revieweeID) {
		this.revieweeID = revieweeID; 
	}
	public String getAdministratorID() {
		return administratorID; 
	}
	public void setAdministratorID(String administratorID) {
		this.administratorID = administratorID; 
	}
	public String getRequestedByID() {
		return requestedByID; 
	}
	public void setRequestedByID(String requestedByID) {
		this.requestedByID = requestedByID; 
	}

    public void assocReview360Light(Review360Light review) {
		reviews.add(review);
    }
    public void dissocReview360Light(Review360Light review) {
		reviews.remove(review);
    }
    protected void _assocReview360Light(Review360Light review) {
	//	this.reviews.add(review);
    //    review.assocReviewSession(this);
    }
    protected void _dissocReview360Light(Review360Light review) {
	//	if(this.reviews.contains(review)) {
	//		review._dissocReviewSession();
//			this.reviews.remove(review);
  //      }

    }
    public Set getReview360Lights(){
    	return reviews;
	}
    public void setReview360Lights(Set reviews) {
		this.reviews = reviews;
    }

}
