/* Generated by Together */

package org.alt60m.cms.model;
//import java.util.Set;
//import java.util.HashSet;
import java.util.Collection;
import java.util.Vector;

/**
 * @persistent 
 * @table cms_CmsCategory
 * @cache-type none
 * @access shared
 * @key-generator UUID
 */
public class CmsCategory {
    /**
     * @sql-type varchar
     * @sql-size 64
     * @primary-key
     */
    private String CmsCategoryID = "";

    /**
     * @sql-type varchar
     * @sql-size 64
     */
    private String parentCategory = "";

    /**
     * @sql-type varchar
     * @sql-size 255
     */
	private String catName = "";
	/**
     * @sql-type varchar
     * @sql-size 255
     */
	private String catDesc = "";

	private String path = "";
    private String pathid = "";

    /** @associates <{CmsFile}>
     * @clientCardinality 0..*
     * @supplierCardinality 0..*
     * @clientRole files
     * @supplierRole categories
     * @undirected
     * @field-name files
     * @field-type org.alt60m.cms.model.CmsFile
	 * @many-table cms_assoc_FileCategory
     * @get-method getFiles
     * @set-method setFiles
     * @sql-name CmsFileID
     * @many-key CmsCategoryID
     */
    private Collection lnkCmsFiles = new Vector();

	public String getCmsCategoryID() {
	        return CmsCategoryID;
	}
	public void setCmsCategoryID(String CmsCategoryID) {
	        this.CmsCategoryID = CmsCategoryID;
	}
	public String getParentCategory() {
	        return parentCategory;
	}
	public void setParentCategory(String parentCategory) {
	        this.parentCategory = parentCategory;
	}
	public String getCatName() {
	        return catName;
	}
	public void setCatName(String catName) {
	        this.catName = catName;
	}
	public String getCatDesc() {
	        return catDesc;
	}
	public void setCatDesc(String catDesc) {
	        this.catDesc = catDesc;
	}
	public String getPath() {
	        return path;
	}
	public void setPath(String path) {
	        this.path = path;
	}
	public String getPathid() {
	        return pathid;
	}
	public void setPathid(String pathid) {
	        this.pathid = pathid;
	}
	public Collection getFiles() {
	        return lnkCmsFiles;
	}
	public void setFiles(Collection files) {
	        this.lnkCmsFiles = files;
	}
}
