/* Generated by Together */

package org.alt60m.ministry;

/** This exception is thrown when condition occurred */
public class MinistryBrokerException extends Exception {
    /** Constructs an Exception without a message. */
    public MinistryBrokerException() {
        super();
    }

    /**
     * Constructs an Exception with a detailed message.
     * @param Message The message associated with the exception.
     */
    public MinistryBrokerException(String message) {
        super(message);
    }

    public MinistryBrokerException(Exception e) {
        super(e.toString());
    }
}
