/* Generated by Together */

package org.alt60m.ministry;
import java.util.*;


public class Regions {

    // Static stuff
    // ****************************************
	// User-readable string
	public static final String[] abbrevRegion = new String[] {"NE", "MA", "MS", "SE", "GL", "UM", "GP", "RR", "NW", "SW"};
	public static final String[] expandedRegion = new String[] {"Northeast", "Mid-Atlantic", "MidSouth", "Southeast", "Great Lakes", "Upper Midwest", "Great Plains Int'l", "Red River", "Greater Northwest", "Pacific Southwest"};


	public static String expandRegion(String abbrev) {
		return org.alt60m.util.TextUtils.translate(abbrevRegion, expandedRegion, abbrev);
	}


	public static void main(String[] args)
	{
        /*
		System.out.println("Expand CA: " + expandStrategy("CA"));
		System.out.println("Expand ca: " + expandStrategy("ca"));
		System.out.println("Expand WS: " + expandStrategy("WS"));
        */
	}

}
