/* Generated by Together */

package org.alt60m.ministry;
import java.util.*;


public class Strategies {

    // Static stuff
    // ****************************************
	// User-readable string
	public static final String[] abbrevStrategies = new String[] { "CA", "SC", "IE", "ID", "II", "WI", "WS", "BR", "MM", "AA", "GR", "CL", "KC" };
	public static final String[] expandedStrategies = new String[] { "Catalytic", "Staffed Campus", "ESM-Epic", "ESM-Destino", "ESM-Impact", "WSN ICS", "WSN STInt", "Bridges", "Military Ministry", "AIA", "Grad Resources", "CLM (Christian Leadership U", "Korean CCC" };


	public static String expandStrategy(String abbrev) {
		return org.alt60m.util.TextUtils.translate(abbrevStrategies, expandedStrategies, abbrev);
	}


/*
    private Hashtable _hash = new Hashtable();
    public setAllStrategies() {
		for(int cnt=0;cnt<abbrevStrategies.length;cnt++) {
            _hash.put(abbrevStrategies[cnt], abbrevStrategies[cnt]);
        }
    }
	public void setStrategy(String abbrev) {
		_hash.put(abbrev, abbrev);
    }
	public String getSetStrategiesAsList() {
    }
*/
	public static void main(String[] args) 
	{
		//System.out.println("All abbrev: " + getAllAbbrevStrategies());
		//System.out.println("All full:   " + getAllStrategies());
		System.out.println("Expand CA: " + expandStrategy("CA"));
		System.out.println("Expand ca: " + expandStrategy("ca"));
		System.out.println("Expand WS: " + expandStrategy("WS"));



	}

}
