/* Generated by Together */

package org.alt60m.ministry.model.locator;
import java.util.Date;
import java.util.Set;
import java.util.HashSet;

/**
 * @rdbPhysicalName Activity
 * @rdbPhysicalPrimaryKeyName PK_Activity
 * @persistent
 * @table ministry_Activity
 * @key-generator UUID
 * @cache-type none
 * @access shared
 */
public class Activity {

    class Status {
		public static final String ACTIVE = "AC";
		public static final String INACTIVE = "IN";
		public static final String KEYCONTACT= "KE";
		public static final String LAUNCHED = "LA";
		public static final String PIONEERING = "PI";
		public static final String TRANSFORMATIONAL = "TR";
		public static final String FORERUNNER = "FR";
    }


    private String status = new String();
    private String strategy = new String();

	public String getStatusFullName() {
		if (status.equalsIgnoreCase(Status.ACTIVE)) return "Active";
		if (status.equalsIgnoreCase(Status.INACTIVE)) return "Inactive";
		if (status.equalsIgnoreCase(Status.KEYCONTACT)) return "Key Contact";
		if (status.equalsIgnoreCase(Status.LAUNCHED)) return "Launched";
		if (status.equalsIgnoreCase(Status.PIONEERING)) return "Pioneering";
		if (status.equalsIgnoreCase(Status.FORERUNNER)) return "Forerunner";
		if (status.equalsIgnoreCase(Status.TRANSFORMATIONAL)) return "Transformational";
        return "Unknown";
    }
	public String getStatus() {
		return status;
	}
	public void setStatus(String status) {
		this.status = status; 
	}
    public boolean isActive() {
		return (!Status.INACTIVE.equalsIgnoreCase(this.status));
    }

    public String getStrategyFullName() {
		return org.alt60m.ministry.Strategies.expandStrategy(getStrategy());
    }
	public String getStrategy() {
		return strategy; 
	}
	public void setStrategy(String strategy) {
		this.strategy = strategy; 
	}
	public TargetArea getTargetArea() {
		return targetArea; 
	}
	public void setTargetArea(TargetArea targetArea) {
		this.targetArea = targetArea;
 	}


    public String getActivityID(){
            return activityID;
        }

    public void setActivityID(String activityID){
            this.activityID = activityID;
        }


    public Set getActivityContacts(){
            return activityContacts;
        }

	public void addActivityContacts(Staff contact) {
		activityContacts.add(contact);
    }


    private LocalLevel team;

    public LocalLevel getTeam(){
            return team;
        }

	public void setTeam(LocalLevel team){
    	this.team = team;
	}


    /**
     * @clientCardinality 0..n
     * @clientRole activities
     * @supplierCardinality 0..1
     * @supplierRole targetArea
     * @label hasActivity 
     * @bidirectional <{Logical_View.org.alt60m.ministry.ejb.TargetArea#doesActivity}>
     * @sql-name fk_targetAreaID
	 */
    private TargetArea targetArea;

    /**
     * @associates <{org.alt60m.ministry.model.Staff}>
     * @field-type org.alt60m.ministry.model.Staff
     * @many-table ministry_assocActivityStaff
     * @sql-name fk_accountNo
     * @many-key fk_activityID
     */
    private Set activityContacts = new HashSet();


	/**
	 * @primary-key
	 */
    private String activityID = new String();
}
