/* Generated by Together */

package org.alt60m.ministry.model.locator;
import java.util.*;
//import java.util.Date;

/**
 * @persistent 
 * @table ministry_TargetArea
 * @key-generator UUID
 * @cache-type none
 * @access shared
 */
public class TargetArea {
	/**
	 * @primary-key
	 */
	private String targetAreaID = new String();
    private String name = new String();
    private String city = new String();
    private String state = new String();
    private String zip = new String();
    private String country = new String();
    private String region = new String();
	private boolean isSecure;

	public String getName() {
		return name; 
	}
	public void setName(String name) {
		this.name = name; 
	}

	public boolean getIsSecure() {
		return isSecure; 
	}
	public void setIsSecure(boolean isSecure) {
		this.isSecure = isSecure; 
	}

	public String getCity() {
		return city; 
	}
	public void setCity(String city) {
		this.city = city; 
	}
	public String getState() {
		return state; 
	}
	public void setState(String state) {
		this.state = state; 
	}
	public String getZip() {
		return zip; 
	}
	public void setZip(String zip) {
		this.zip = zip; 
	}
	public String getCountry() {
		return country; 
	}
	public String getRegion() {
		return region; 
	}
	public void setRegion(String region) {
		this.region = region; 
	}
	public void setCountry(String country) {
		this.country = country; 
	}
	public Collection getActivities() {
		return activities; 
	}
	public void setActivities(Collection activities) {
		this.activities = activities; 
	}
    public void assocActivity(Activity activity) {
		if(!this.activities.contains(activity)) {
			this.activities.add(activity);
        }
        activity.setTargetArea(this);
    }
    public void dissocActivity(Activity activity) {
		this.activities.remove(activity);
        activity.setTargetArea(null);
    }

    public String getTargetAreaID(){
            return targetAreaID;
        }

    public void setTargetAreaID(String targetAreaID){
            this.targetAreaID = targetAreaID;
        }


    /**
     * @associates <{Activity}>
     * @clientCardinality 0..1
     * @supplierCardinality 0..*
     * @label activities
     * @undirected
     * @field-type org.alt60m.ministry.model.Activity
     * @many-key fk_targetAreaID
     */
    private Collection activities = new Vector();
}
