/* Generated by Together */

package org.alt60m.hr.review360.model.dbio;

import com.kenburcham.framework.dbio.DBIOEntity;
import com.kenburcham.framework.dbio.DBIOEntityException;

import org.alt60m.ministry.model.dbio.Staff;

import java.util.Date;

/**
 * @persistent 
 * @table hr_review360_Review360
 * @cache-type none
 * @access shared
 * @key-generator UUID
 */
public class Review360 extends DBIOEntity {
	/**
     * @field-type org.alt60m.hr.review360.model.ReviewSession
     * @sql-type varchar
     * @sql-size 64
     * @sql-name fk_ReviewSessionId
     * @sql-index
     * @set-method assocReviewSession
     * @get-method getReviewSession
     */
    private String sessionId = "";

	/**
     * @sql-type varchar
     * @sql-size 64
     * @primary-key
     */
    private String review360Id = "";

	/**
     * @sql-type varchar
     * @sql-size 64
     */
	private String reviewedById = "";
	
	private String reviewedByTitle = "";
	private String reviewedByFirstName = "";
	private String reviewedByLastName = "";
	private String reviewedByEmail = "";
	//private String reviewedByIsMale = "";
	//private boolean reviewedByIsStaff =false;
	
	
	private Date dateStarted = null;
	private Date dateCompleted = null;
	private Date dateDue = null;

	/**
     * @sql-type varchar
     * @sql-size 128
     */
	private String currentPosition = "";
	/**
     * @sql-type varchar
     * @sql-size 128
     */
	private String leadershipLevel = "";
	/**
     * @sql-type varchar
     * @sql-size 128
     */
	private String relationship = "";
	/**
     * @Xsql-type varchar
     * @Xsql-size 2048
     */
	private String q1 = "";
	private int q2;
	/**
     * @Xsql-type varchar
     * @Xsql-size 2048
     */
	private String q3 = "";
	/**
     * @Xsql-type varchar
     * @Xsql-size 2048
     */
	private String q4 = "";
	/**
     * @Xsql-type varchar
     * @Xsql-size 2048
     */
	private String q5 = "";
	/**
     * @Xsql-type varchar
     * @Xsql-size 2048
     */
	private String q6 = "";
	/**
     * @Xsql-type varchar
     * @Xsql-size 2048
     */
	private String q7 = "";
	private int q8;
	/**
     * @Xsql-type varchar
     * @Xsql-size 2048
     */
	private String q9 = "";
	private int q10;
	/**
     * @Xsql-type varchar
     * @Xsql-size 2048
     */
	private String q11 = "";
	private int q12;
	/**
     * @Xsql-type varchar
     * @Xsql-size 2048
     */
	private String q13 = "";
	private int q14;
	/**
     * @Xsql-type varchar
     * @Xsql-size 2048
     */
	private String q15 = "";
	private int q16;
	/**
     * @Xsql-type varchar
     * @Xsql-size 2048
     */
	private String q17 = "";
	private int q18;
	/**
     * @Xsql-type varchar
     * @Xsql-size 2048
     */
	private String q19 = "";
	private int q20;
	/**
     * @Xsql-type varchar
     * @Xsql-size 2048
     */
	private String q21 = "";
	private int q22;
	/**
     * @Xsql-type varchar
     * @Xsql-size 2048
     */
	private String q23 = "";
	private int q24;
	/**
     * @Xsql-type varchar
     * @Xsql-size 2048
     */
	private String q25 = "";
	/**
     * @Xsql-type varchar
     * @Xsql-size 2048
     */
	private String q26 = "";
	/**
     * @Xsql-type varchar
     * @Xsql-size 2048
     */
	private String q27 = "";
	/**
     * @Xsql-type varchar
     * @Xsql-size 2048
     */
	private String q28f1 = "";
	private int q28f2;
	/**
     * @Xsql-type varchar
     * @Xsql-size 2048
     */
	private String q28l1 = "";
	private int q28l2;
	/**
     * @Xsql-type varchar
     * @Xsql-size 2048
     */
	private String q28o1 = "";
	private int q28o2;
	/**
     * @Xsql-type varchar
     * @Xsql-size 2048
     */
	private String q28a1 = "";
	private int q28a2;
	/**
     * @Xsql-type varchar
     * @Xsql-size 2048
     */
	private String q28t1 = "";
	private int q28t2;
	/**
     * @Xsql-type varchar
     * @Xsql-size 2048
     */
	private String q28s1 = "";
	private int q28s2;
	/**
     * @Xsql-type varchar
     * @Xsql-size 2048
     */
	private String q29 = "";
	/**
     * @Xsql-type varchar
     * @Xsql-size 2048
     */
	private String q30 = "";
	/**
     * @Xsql-type varchar
     * @Xsql-size 2048
     */
	private String q31 = "";
	/**
     * @Xsql-type varchar
     * @Xsql-size 2048
     */
	private String q32 = "";
	/**
     * @Xsql-type varchar
     * @Xsql-size 2048
     */
	private String q33 = "";
	/**
     * @Xsql-type varchar
     * @Xsql-size 2048
     */
	private String q34 = "";
	
	public Review360() { }
	public Review360(String id)
	{ 
		review360Id = id;
		select();
	}
	
	public boolean isPKEmpty() { return this.review360Id.equals(""); }
	
	public void localinit() throws DBIOEntityException {

		String table = "hr_review360_Review360";

		setMetadata("Review360Id","Review360ID","IDENTITY");

		setMetadata("ReviewedById","reviewedByID",table);
		
		setMetadata("ReviewedByTitle","reviewedByTitle",table);
		setMetadata("ReviewedByFirstName","reviewedByFirstName",table);
		setMetadata("ReviewedByLastName","reviewedByLastName",table);
		setMetadata("ReviewedByEmail","reviewedByEmail",table);
		//setMetadata("ReviewedByIsStaff","reviewedByIsStaff",table);
		//setMetadata("ReviewedByIsMale","reviewedByIsMale",table);
		
		
		
		setMetadata("ReviewSessionId","fk_ReviewSessionID",table);

		setMetadata("DateStarted","dateStarted",table);
		setMetadata("DateCompleted","dateCompleted",table);
		setMetadata("DateDue","dateDue",table);
		setMetadata("CurrentPosition","currentPosition",table);
		setMetadata("LeadershipLevel","leadershipLevel",table);
		setMetadata("Relationship","relationship",table);
		
		setMetadata("Q1","q1",table);
		setMetadata("Q2","q2",table);
		setMetadata("Q3","q3",table);
		setMetadata("Q4","q4",table);
		setMetadata("Q5","q5",table);
		setMetadata("Q6","q6",table);
		setMetadata("Q7","q7",table);
		setMetadata("Q8","q8",table);
		setMetadata("Q9","q9",table);
		setMetadata("Q10","q10",table);
		setMetadata("Q11","q11",table);
		setMetadata("Q12","q12",table);
		setMetadata("Q13","q13",table);
		setMetadata("Q14","q14",table);
		setMetadata("Q15","q15",table);
		setMetadata("Q16","q16",table);
		setMetadata("Q17","q17",table);
		setMetadata("Q18","q18",table);
		setMetadata("Q19","q19",table);
		setMetadata("Q20","q20",table);
		setMetadata("Q21","q21",table);
		setMetadata("Q22","q22",table);
		setMetadata("Q23","q23",table);
		setMetadata("Q24","q24",table);
		setMetadata("Q25","q25",table);
		setMetadata("Q26","q26",table);
		setMetadata("Q27","q27",table);
		setMetadata("Q28f1","q28f1",table);
		setMetadata("Q28f2","q28f2",table);
		setMetadata("Q28l1","q28l1",table);
		setMetadata("Q28l2","q28l2",table);
		setMetadata("Q28o1","q28o1",table);
		setMetadata("Q28o2","q28o2",table);
		setMetadata("Q28a1","q28a1",table);
		setMetadata("Q28a2","q28a2",table);
		setMetadata("Q28t1","q28t1",table);
		setMetadata("Q28t2","q28t2",table);
		setMetadata("Q28s1","q28s1",table);
		setMetadata("Q28s2","q28s2",table);
		setMetadata("Q29","q29",table);
		setMetadata("Q30","q30",table);
		setMetadata("Q31","q31",table);
		setMetadata("Q32","q32",table);
		setMetadata("Q33","q33",table);
		setMetadata("Q34","q34",table);

		setAutodetectProperties(false);
		
	}

    public String getReview360Id() { return review360Id; }
    public int getReview360IdInt() {  
    	if(review360Id != null && !review360Id.equals(""))
			return Integer.parseInt(review360Id);
    	else
    		return -1;
    }

    public void setReview360Id(String review360Id) { this.review360Id = review360Id; }
    public void setReview360Id(int review360Id) { this.review360Id = Integer.toString(review360Id); }
	
	// encodes the object's review360Id and returns it.
	// used for emailing the review360Id as a hyperlink.
	public String encodeReview360ID() {
		long coefficient = 2125551212L;  // largest integer is: 214 748 3647
		long revID = (long) getReview360IdInt();
		Long result = new Long (coefficient * revID);
		return result.toString();
	}

	// Given an encoded review360Id, decodes it back to a form that can be used for query on review360Id field
	public String decodeReview360ID(String encRevID) {
		long coefficient = 2125551212L;  // largest integer is: 214 748 3647
		long revID = Long.valueOf(encRevID).longValue();
		Long result = new Long (revID/ coefficient);
		return result.toString();
	}

    
	public String getReviewedById() { return reviewedById; }
	public void setReviewedById(String reviewedById) { this.reviewedById = reviewedById; }
	public Staff getReviewedBy(){ return new Staff(reviewedById); }
	public void setReviewedBy(Staff s) { this.reviewedById = s.getAccountNo(); }
	public void assocReviewedBy(Staff s) { setReviewedBy(s); }
	public void dissocReviewedBy(Staff s) { setReviewedById(""); }
	
	
	public String getReviewedByTitle() { return reviewedByTitle; }
	public void setReviewedByTitle(String reviewedByTitle) { this.reviewedByTitle = reviewedByTitle; }
	public String getReviewedByFirstName() { return reviewedByFirstName; }
	public void setReviewedByFirstName(String reviewedByFirstName) { this.reviewedByFirstName = reviewedByFirstName; }
	public String getReviewedByLastName() { return reviewedByLastName; }
	public void setReviewedByLastName(String reviewedByLastName) { this.reviewedByLastName = reviewedByLastName; }
	public String getReviewedByEmail() { return reviewedByEmail; }
	public void setReviewedByEmail(String reviewedByEmail) { this.reviewedByEmail = reviewedByEmail; }
	
	//public String getReviewedByIsMale() { return reviewedByIsMale; }
	//public void setReviewedByIsMale(String reviewedByIsMale) { this.reviewedByIsMale = reviewedByIsMale; }
	//public boolean getReviewedByIsStaff() { return reviewedByIsStaff; }
	//public void setReviewedByIsStaff(boolean reviewedByIsStaff) { this.reviewedByIsStaff = reviewedByIsStaff; }
	
	
	public Date getDateStarted() { return dateStarted; }
	public void setDateStarted(Date dateStarted) { this.dateStarted = org.alt60m.util.DateUtils.clearTimeFromDate(dateStarted); }
	
	public Date getDateCompleted() { return dateCompleted; }
	public void setDateCompleted(Date dateCompleted) { this.dateCompleted = org.alt60m.util.DateUtils.clearTimeFromDate(dateCompleted); }
	
	public Date getDateDue() { return dateDue; }
	public void setDateDue(Date dateDue) { this.dateDue = org.alt60m.util.DateUtils.clearTimeFromDate(dateDue); }
	
	public String getCurrentPosition() { return currentPosition; }
	public void setCurrentPosition(String currentPosition) { this.currentPosition = currentPosition; }
	
	public String getLeadershipLevel() { return leadershipLevel; }
	public void setLeadershipLevel(String leadershipLevel) { this.leadershipLevel = leadershipLevel; }
	
	public String getRelationship() { return relationship; }
	public void setRelationship(String relationship) { this.relationship = relationship; }
	
	public String getQ1() { return q1; }
	public void setQ1(String q1) { this.q1 = q1; }
	
	public int getQ2() { return q2; }
	public void setQ2(int q2) { this.q2 = q2; }
	
	public String getQ3() { return q3; }
	public void setQ3(String q3) { this.q3 = q3; }
	
	public String getQ4() { return q4; }
	public void setQ4(String q4) { this.q4 = q4; }
	
	public String getQ5() { return q5; }
	public void setQ5(String q5) { this.q5 = q5; }
	
	public String getQ6() { return q6; }
	public void setQ6(String q6) { this.q6 = q6; }
	
	public String getQ7() { return q7; }
	public void setQ7(String q7) { this.q7 = q7; }
	
	public int getQ8() { return q8; }
	public void setQ8(int q8) { this.q8 = q8; }
	
	public String getQ9() { return q9; }
	public void setQ9(String q9) { this.q9 = q9; }
	
	public int getQ10() { return q10; }
	public void setQ10(int q10) { this.q10 = q10; }
	
	public String getQ11() { return q11; }
	public void setQ11(String q11) { this.q11 = q11; }
	
	public int getQ12() { return q12; }
	public void setQ12(int q12) { this.q12 = q12; }
	
	public String getQ13() { return q13; }
	public void setQ13(String q13) { this.q13 = q13; }
	
	public int getQ14() { return q14; }
	public void setQ14(int q14) { this.q14 = q14; }
	
	public String getQ15() { return q15; }
	public void setQ15(String q15) { this.q15 = q15; }
	
	public int getQ16() { return q16; }
	public void setQ16(int q16) { this.q16 = q16; }
	
	public String getQ17() { return q17; }
	public void setQ17(String q17) { this.q17 = q17; }
	
	public int getQ18() { return q18; }
	public void setQ18(int q18) { this.q18 = q18; }
	
	public String getQ19() { return q19; }
	public void setQ19(String q19) { this.q19 = q19; }
	
	public int getQ20() { return q20; }
	public void setQ20(int q20) { this.q20 = q20; }
	
	public String getQ21() { return q21; }
	public void setQ21(String q21) { this.q21 = q21; }
	
	public int getQ22() { return q22; }
	public void setQ22(int q22) { this.q22 = q22; }
	
	public String getQ23() { return q23; }
	public void setQ23(String q23) { this.q23 = q23; }
	
	public int getQ24() { return q24; }
	public void setQ24(int q24) { this.q24 = q24; }
	
	public String getQ25() { return q25; }
	public void setQ25(String q25) { this.q25 = q25; }
	
	public String getQ26() { return q26; }
	public void setQ26(String q26) { this.q26 = q26; }
	
	public String getQ27() { return q27; }
	public void setQ27(String q27) { this.q27 = q27; }
	
	public String getQ28f1() { return q28f1; }
	public void setQ28f1(String q28f1) { this.q28f1 = q28f1; }
	
	public int getQ28f2() {	return q28f2; }
	public void setQ28f2(int q28f2) { this.q28f2 = q28f2; }
	
	public String getQ28l1() { return q28l1; }
	public void setQ28l1(String q28l1) { this.q28l1 = q28l1; }
	
	public int getQ28l2() { return q28l2; }
	public void setQ28l2(int q28l2) { this.q28l2 = q28l2; }
	
	public String getQ28o1() { return q28o1; }
	public void setQ28o1(String q28o1) { this.q28o1 = q28o1; }
	
	public int getQ28o2() { return q28o2; }
	public void setQ28o2(int q28o2) { this.q28o2 = q28o2; }
	
	public String getQ28a1() { return q28a1; }
	public void setQ28a1(String q28a1) { this.q28a1 = q28a1; }
	
	public int getQ28a2() {	return q28a2; }
	public void setQ28a2(int q28a2) { this.q28a2 = q28a2; }
	
	public String getQ28t1() { return q28t1; }
	public void setQ28t1(String q28t1) { this.q28t1 = q28t1; }
	
	public int getQ28t2() {	return q28t2; }
	public void setQ28t2(int q28t2) { this.q28t2 = q28t2; }
	
	public String getQ28s1() { return q28s1; }
	public void setQ28s1(String q28s1) { this.q28s1 = q28s1; }
	
	public int getQ28s2() {	return q28s2; }
	public void setQ28s2(int q28s2) { this.q28s2 = q28s2; }
	
	public String getQ29() { return q29; }
	public void setQ29(String q29) { this.q29 = q29; }
	
	public String getQ30() { return q30; }
	public void setQ30(String q30) { this.q30 = q30; }
	
	public String getQ31() { return q31; }
	public void setQ31(String q31) { this.q31 = q31; }
	
	public String getQ32() { return q32; }
	public void setQ32(String q32) { this.q32 = q32; }
	
	public String getQ33() { return q33; }
	public void setQ33(String q33) { this.q33 = q33; }
	
	public String getQ34() { return q34; }
	public void setQ34(String q34) { this.q34 = q34; }

    public String getReviewSessionId(){ return sessionId; }
    public void setReviewSessionId(String sessionId) { this.sessionId = sessionId; }
    public ReviewSession getReviewSession(){ return new ReviewSession(sessionId); }
    public void setReviewSession(ReviewSession session) { this.sessionId = session.getReviewSessionId(); }
    public void dissocReviewSession(){ this.sessionId = ""; }
	public void assocReviewSession(ReviewSession session){ setReviewSession(session); }

	
	
}
