# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define() do

  create_table "ap_personurls", :id => false, :force => true do |t|
    t.column "personURLID", :integer, :default => 0, :null => false
    t.column "URL", :string, :limit => 500
    t.column "description", :string
    t.column "serviceAPI", :string
    t.column "fk_PersonID", :integer, :default => 0, :null => false
  end

  create_table "ap_projecturls", :id => false, :force => true do |t|
    t.column "projectURLID", :integer, :default => 0, :null => false
    t.column "URL", :string, :limit => 500
    t.column "description", :string
    t.column "serviceAPI", :string
    t.column "fk_WsnProjectID", :integer, :default => 0, :null => false
  end

  create_table "ap_signup", :id => false, :force => true do |t|
    t.column "ambassadorPledgeID", :integer, :default => 0, :null => false
    t.column "pledgeDate", :datetime
    t.column "fk_PersonID", :integer, :default => 0, :null => false
  end

  create_table "cms_cmscategory", :id => false, :force => true do |t|
    t.column "CmsCategoryID", :integer, :default => 0, :null => false
    t.column "oldPrimaryKey", :string, :limit => 64
    t.column "parentCategory", :integer
    t.column "catName", :string, :limit => 256
    t.column "catDesc", :string, :limit => 2000
    t.column "path", :string, :limit => 2000
    t.column "pathid", :string, :limit => 2000
  end

  create_table "crs_answer", :id => false, :force => true do |t|
    t.column "answerID", :integer, :default => 0, :null => false
    t.column "body", :string, :limit => 7000
    t.column "fk_QuestionID", :integer
    t.column "fk_RegistrationID", :integer
  end

  create_table "crs_childregistration", :id => false, :force => true do |t|
    t.column "childRegistrationID", :integer, :default => 0, :null => false
    t.column "firstName", :string, :limit => 80
    t.column "lastName", :string, :limit => 80
    t.column "gender", :string, :limit => 1
    t.column "age", :integer
    t.column "arriveDate", :datetime
    t.column "birthDate", :datetime
    t.column "leaveDate", :datetime
    t.column "inChildCare", :string, :limit => 1
    t.column "fk_RegistrationID", :integer
  end

  create_table "crs_conference", :id => false, :force => true do |t|
    t.column "conferenceID", :integer, :default => 0, :null => false
    t.column "createDate", :datetime
    t.column "acceptScholarships", :string, :limit => 1
    t.column "authnetPassword", :string, :limit => 200
    t.column "preRegStart", :datetime
    t.column "preRegEnd", :datetime
    t.column "defaultDateStaffArrive", :datetime
    t.column "defaultDateStaffLeave", :datetime
    t.column "defaultDateGuestArrive", :datetime
    t.column "defaultDateGuestLeave", :datetime
    t.column "defaultDateStudentArrive", :datetime
    t.column "defaultDateStudentLeave", :datetime
    t.column "masterDefaultDateArrive", :datetime
    t.column "masterDefaultDateLeave", :datetime
    t.column "ministryType", :string, :limit => 2
    t.column "isCloaked", :string, :limit => 1
    t.column "onsiteCost", :float
    t.column "commuterCost", :float
    t.column "preRegDeposit", :float
    t.column "discountFullPayment", :float
    t.column "discountEarlyReg", :float
    t.column "discountEarlyRegDate", :datetime
    t.column "checkPayableTo", :string, :limit => 40
    t.column "merchantAcctNum", :string, :limit => 64
    t.column "backgroundColor3", :string, :limit => 6
    t.column "backgroundColor2", :string, :limit => 6
    t.column "highlightColor2", :string, :limit => 6
    t.column "requiredColor", :string, :limit => 6
    t.column "acceptVisa", :string, :limit => 1
    t.column "acceptMasterCard", :string, :limit => 1
    t.column "acceptAmericanExpress", :string, :limit => 1
    t.column "acceptDiscover", :string, :limit => 1
    t.column "staffProfileNumber", :integer
    t.column "staffProfileReqNumber", :integer
    t.column "guestProfileNumber", :integer
    t.column "guestProfileReqNumber", :integer
    t.column "studentProfileNumber", :integer
    t.column "studentProfileReqNumber", :integer
    t.column "askStudentChildren", :string, :limit => 1
    t.column "askStaffChildren", :string, :limit => 1
    t.column "askGuestChildren", :string, :limit => 1
    t.column "studentLabel", :string, :limit => 64
    t.column "staffLabel", :string, :limit => 64
    t.column "guestLabel", :string, :limit => 64
    t.column "studentDesc", :string
    t.column "staffDesc", :string
    t.column "guestDesc", :string
    t.column "askStudentSpouse", :string, :limit => 1
    t.column "askStaffSpouse", :string, :limit => 1
    t.column "askGuestSpouse", :string, :limit => 1
    t.column "attributesAsked", :string, :limit => 30
    t.column "name", :string, :limit => 64
    t.column "theme", :string, :limit => 128
    t.column "password", :string, :limit => 20
    t.column "staffPassword", :string, :limit => 20
    t.column "region", :string, :limit => 3
    t.column "briefDescription", :text
    t.column "contactName", :string, :limit => 60
    t.column "contactEmail", :string, :limit => 50
    t.column "contactPhone", :string, :limit => 24
    t.column "contactAddress1", :string, :limit => 35
    t.column "contactAddress2", :string, :limit => 35
    t.column "contactCity", :string, :limit => 30
    t.column "contactState", :string, :limit => 6
    t.column "contactZip", :string, :limit => 10
    t.column "splashPageURL", :string, :limit => 128
    t.column "confImageId", :string, :limit => 64
    t.column "fontFace", :string, :limit => 64
    t.column "backgroundColor", :string, :limit => 6
    t.column "foregroundColor", :string, :limit => 6
    t.column "highlightColor", :string, :limit => 6
    t.column "confirmationEmail", :text
    t.column "acceptCreditCards", :string, :limit => 1
    t.column "acceptEChecks", :string, :limit => 1
  end

  create_table "crs_customitem", :id => false, :force => true do |t|
    t.column "customItemID", :integer, :default => 0, :null => false
    t.column "title", :string, :limit => 128
    t.column "text", :string, :limit => 1000
    t.column "displayOrder", :integer
    t.column "fk_ConferenceID", :integer
  end

  create_table "crs_merchandise", :id => false, :force => true do |t|
    t.column "merchandiseID", :integer, :default => 0, :null => false
    t.column "name", :string, :limit => 128
    t.column "note", :string
    t.column "amount", :float
    t.column "required", :string, :limit => 1
    t.column "registrationType", :string, :limit => 50
    t.column "displayOrder", :integer
    t.column "fk_ConferenceID", :integer
    t.column "fk_RegistrationTypeID", :integer
  end

  create_table "crs_payment", :id => false, :force => true do |t|
    t.column "paymentID", :integer, :default => 0, :null => false
    t.column "paymentDate", :datetime
    t.column "debit", :float
    t.column "credit", :float
    t.column "type", :string, :limit => 80
    t.column "authCode", :string, :limit => 80
    t.column "businessUnit", :string, :limit => 50
    t.column "dept", :string, :limit => 50
    t.column "operatingUnit", :string, :limit => 50
    t.column "project", :string, :limit => 50
    t.column "accountNo", :string, :limit => 80
    t.column "comment", :string
    t.column "posted", :string, :limit => 1
    t.column "postedDate", :datetime
    t.column "fk_RegistrationID", :integer
  end

  create_table "crs_question", :id => false, :force => true do |t|
    t.column "questionID", :integer, :default => 0, :null => false
    t.column "registrationType", :string, :limit => 50
    t.column "required", :string, :limit => 1
    t.column "displayOrder", :integer
    t.column "fk_ConferenceID", :integer
    t.column "fk_QuestionTextID", :integer
    t.column "fk_RegistrationTypeID", :integer
  end

  create_table "crs_questiontext", :id => false, :force => true do |t|
    t.column "questionTextID", :integer, :default => 0, :null => false
    t.column "body", :string, :limit => 7000
    t.column "answerType", :string, :limit => 50
    t.column "status", :string, :limit => 50
    t.column "oldID", :integer
  end

  create_table "crs_registration", :id => false, :force => true do |t|
    t.column "registrationID", :integer, :default => 0, :null => false
    t.column "registrationDate", :datetime
    t.column "registrationType", :string, :limit => 80
    t.column "preRegistered", :string, :limit => 1
    t.column "newPersonID", :integer
    t.column "fk_ConferenceID", :integer
    t.column "arriveDate", :datetime
    t.column "leaveDate", :datetime
    t.column "additionalRooms", :integer
    t.column "spouseComing", :integer
    t.column "spouseRegistrationID", :integer
    t.column "registeredFirst", :string, :limit => 1
    t.column "isOnsite", :string, :limit => 1
    t.column "fk_RegistrationTypeID", :integer
    t.column "fk_PersonID", :integer
  end

  create_table "crs_registrationtype", :id => false, :force => true do |t|
    t.column "registrationTypeID", :integer, :default => 0, :null => false
    t.column "label", :string, :limit => 64
    t.column "askChildCare", :string, :limit => 1
    t.column "askAdditionalRooms", :string, :limit => 1
    t.column "allowCommute", :string, :limit => 1
    t.column "displayOrder", :integer
    t.column "profileNumber", :integer
    t.column "profileReqNumber", :integer
    t.column "registrationType", :string, :limit => 10
    t.column "fk_ConferenceID", :integer
    t.column "acceptChecks", :string, :limit => 1
    t.column "description", :string, :limit => 256
    t.column "defaultDateArrive", :datetime
    t.column "defaultDateLeave", :datetime
    t.column "preRegStart", :datetime
    t.column "preRegEnd", :datetime
    t.column "singlePreRegDeposit", :float
    t.column "singleOnsiteCost", :float
    t.column "singleCommuteCost", :float
    t.column "singleDiscountFullPayment", :float
    t.column "singleDiscountEarlyReg", :float
    t.column "singleDiscountEarlyRegDate", :datetime
    t.column "marriedPreRegDeposit", :float
    t.column "marriedOnsiteCost", :float
    t.column "marriedCommuteCost", :float
    t.column "marriedDiscountFullPayment", :float
    t.column "marriedDiscountEarlyReg", :float
    t.column "marriedDiscountEarlyRegDate", :datetime
    t.column "acceptEChecks", :string, :limit => 1
    t.column "acceptScholarships", :string, :limit => 1
    t.column "acceptStaffAcctTransfer", :string, :limit => 1
    t.column "acceptMinistryAcctTransfer", :string, :limit => 1
    t.column "acceptCreditCards", :string, :limit => 1
    t.column "askChildren", :string, :limit => 1
    t.column "askSpouse", :string, :limit => 1
  end

  create_table "crs_report", :id => false, :force => true do |t|
    t.column "reportID", :integer, :default => 0, :null => false
    t.column "query", :string, :limit => 1000
    t.column "xsl", :string
    t.column "name", :string
    t.column "reportGroup", :integer
    t.column "sorts", :string, :limit => 1000
    t.column "sortNames", :string, :limit => 1000
  end

  create_table "fsk_allocations", :force => true do |t|
    t.column "ssm_id", :integer
    t.column "region_id", :string, :limit => 2
    t.column "impactAllotment", :string, :limit => 12
    t.column "forerunnerAllotment", :string, :limit => 12
    t.column "regionalAllotment", :string, :limit => 12
    t.column "regionallyRaised", :string, :limit => 12
    t.column "locallyRaised", :string, :limit => 12
    t.column "allocationYear", :string, :limit => 10
    t.column "nationalNotes", :string, :limit => 1024
    t.column "impactNotes", :string, :limit => 1024
    t.column "forerunnerNotes", :string, :limit => 1024
    t.column "regionalNotes", :string, :limit => 1024
    t.column "localNotes", :string, :limit => 1024
    t.column "version", :integer
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "fsk_distributions", :id => false, :force => true do |t|
    t.column "distributionID", :integer, :default => 0, :null => false
    t.column "oldPrimaryKey", :string, :limit => 64
    t.column "campusName", :string, :limit => 128
    t.column "totalKits", :integer
    t.column "version", :integer
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
    t.column "fk_Allocation", :integer
  end

  create_table "fsk_kitcategories", :force => true do |t|
    t.column "name", :string, :limit => 50, :default => "", :null => false
    t.column "description", :string, :limit => 2000
    t.column "version", :integer
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "fsk_lineitems", :force => true do |t|
    t.column "product_id", :integer, :default => 0, :null => false
    t.column "order_id", :integer, :default => 0, :null => false
    t.column "quantity", :integer, :default => 0, :null => false
    t.column "version", :integer
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  add_index "fsk_lineitems", ["product_id"], :name => "IX_fsk_LineItems"

  create_table "fsk_orders", :force => true do |t|
    t.column "locationName", :string, :limit => 128
    t.column "updated_at", :datetime
    t.column "allocation_id", :integer
    t.column "dateCreated", :datetime
    t.column "dateUpdated", :datetime
    t.column "contactFirstName", :string, :limit => 30
    t.column "contactLastName", :string, :limit => 30
    t.column "contactPhone", :string, :limit => 24
    t.column "contactCell", :string, :limit => 24
    t.column "contactEmail", :string, :limit => 50
    t.column "shipName", :string, :limit => 30
    t.column "shipAddress1", :string, :limit => 35
    t.column "shipAddress2", :string, :limit => 35
    t.column "shipCity", :string, :limit => 30
    t.column "shipState", :string, :limit => 6
    t.column "shipZip", :string, :limit => 10
    t.column "shipPhone", :string, :limit => 24
    t.column "totalKits", :integer
    t.column "businessUnit", :string, :limit => 10
    t.column "operatingUnit", :string, :limit => 10
    t.column "deptId", :string, :limit => 10
    t.column "projectId", :string, :limit => 10
    t.column "type", :string, :limit => 10
    t.column "orderYear", :string, :limit => 10
    t.column "ssm_id", :integer
    t.column "version", :integer
    t.column "created_at", :datetime
  end

  create_table "fsk_products", :force => true do |t|
    t.column "name", :string, :limit => 50
    t.column "description", :string, :limit => 4000
    t.column "image_filename", :string, :limit => 1000
    t.column "price", :float
    t.column "quantity", :string, :limit => 10
    t.column "version", :integer
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
    t.column "kitCategory_id", :integer, :default => 0, :null => false
  end

  add_index "fsk_products", ["kitCategory_id"], :name => "FK_fsk_products_1"

  create_table "hr_ms_payment", :id => false, :force => true do |t|
    t.column "paymentID", :integer, :default => 0, :null => false
    t.column "oldPrimaryKey", :string, :limit => 128
    t.column "paymentDate", :datetime
    t.column "debit", :float
    t.column "credit", :float
    t.column "type", :string, :limit => 160
    t.column "authCode", :string, :limit => 160
    t.column "businessUnit", :string, :limit => 100
    t.column "dept", :string, :limit => 100
    t.column "region", :string, :limit => 100
    t.column "project", :string, :limit => 100
    t.column "accountNo", :string, :limit => 160
    t.column "comment", :string, :limit => 510
    t.column "posted", :boolean
    t.column "postedDate", :datetime
    t.column "fk_WsnApplicationID", :integer
    t.column "paymentFor", :string, :limit => 100
  end

  create_table "hr_review360_review360", :id => false, :force => true do |t|
    t.column "Review360ID", :integer, :default => 0, :null => false
    t.column "oldPrimaryKey", :string, :limit => 64
    t.column "q18", :integer
    t.column "q19", :text
    t.column "q20", :integer
    t.column "q21", :text
    t.column "q22", :integer
    t.column "q23", :text
    t.column "q24", :integer
    t.column "q25", :text
    t.column "q26", :text
    t.column "q27", :text
    t.column "q28f1", :text
    t.column "q28f2", :integer
    t.column "q28l1", :text
    t.column "q28l2", :integer
    t.column "q28o1", :text
    t.column "q28o2", :integer
    t.column "q28a1", :text
    t.column "q28a2", :integer
    t.column "q28t1", :text
    t.column "q28t2", :integer
    t.column "q28s1", :text
    t.column "q28s2", :integer
    t.column "q29", :text
    t.column "q30", :text
    t.column "q31", :text
    t.column "q32", :text
    t.column "q33", :text
    t.column "q34", :text
    t.column "fk_ReviewSessionID", :integer
    t.column "reviewedByTitle", :string, :limit => 5
    t.column "reviewedByFirstName", :string, :limit => 30
    t.column "reviewedByLastName", :string, :limit => 30
    t.column "reviewedByEmail", :string, :limit => 50
    t.column "reviewedByID", :string, :limit => 64
    t.column "dateStarted", :datetime
    t.column "dateCompleted", :datetime
    t.column "dateDue", :datetime
    t.column "currentPosition", :string, :limit => 128
    t.column "leadershipLevel", :string, :limit => 128
    t.column "relationship", :string, :limit => 128
    t.column "q1", :text
    t.column "q2", :integer
    t.column "q3", :text
    t.column "q4", :text
    t.column "q5", :text
    t.column "q6", :text
    t.column "q7", :text
    t.column "q8", :integer
    t.column "q9", :text
    t.column "q10", :integer
    t.column "q11", :text
    t.column "q12", :integer
    t.column "q13", :text
    t.column "q14", :integer
    t.column "q15", :text
    t.column "q16", :integer
    t.column "q17", :text
  end

  create_table "hr_review360_review360light", :id => false, :force => true do |t|
    t.column "Review360LightID", :integer, :default => 0, :null => false
    t.column "oldPrimaryKey", :string, :limit => 64
    t.column "reviewedByID", :string, :limit => 64
    t.column "reviewedByTitle", :string, :limit => 5
    t.column "reviewedByFirstName", :string, :limit => 30
    t.column "reviewedByLastName", :string, :limit => 30
    t.column "reviewedByEmail", :string, :limit => 50
    t.column "dateStarted", :datetime
    t.column "dateCompleted", :datetime
    t.column "dateDue", :datetime
    t.column "currentPosition", :string, :limit => 128
    t.column "leadershipLevel", :string, :limit => 128
    t.column "relationship", :string, :limit => 128
    t.column "q1", :text
    t.column "q2", :text
    t.column "q3", :text
    t.column "q4", :text
    t.column "q5", :text
    t.column "q6", :text
    t.column "q7", :text
    t.column "q8", :text
    t.column "q9", :text
    t.column "fk_ReviewSessionLightID", :integer
  end

  create_table "hr_review360_reviewsession", :id => false, :force => true do |t|
    t.column "ReviewSessionID", :integer, :default => 0, :null => false
    t.column "oldPrimaryKey", :string, :limit => 64
    t.column "name", :string, :limit => 80
    t.column "purpose", :string
    t.column "dateDue", :datetime
    t.column "dateStarted", :datetime
    t.column "revieweeID", :string, :limit => 128
    t.column "administratorID", :string, :limit => 128
    t.column "requestedByID", :string, :limit => 128
  end

  create_table "hr_review360_reviewsessionlight", :id => false, :force => true do |t|
    t.column "ReviewSessionLightID", :integer, :default => 0, :null => false
    t.column "oldPrimaryKey", :string, :limit => 64
    t.column "name", :string, :limit => 80
    t.column "purpose", :string
    t.column "dateDue", :datetime
    t.column "dateStarted", :datetime
    t.column "revieweeID", :string, :limit => 128
    t.column "administratorID", :string, :limit => 128
    t.column "requestedByID", :string, :limit => 128
  end

  create_table "hr_si_application", :id => false, :force => true do |t|
    t.column "applicationID", :integer, :default => 0, :null => false
    t.column "oldPrimaryKey", :string, :limit => 64
    t.column "previousMinistryExperience", :text
    t.column "ministryTraining", :text
    t.column "evangelismAttitude", :text
    t.column "isEvangelismTrainable", :integer
    t.column "participationExplanation", :text
    t.column "isFamiliarFourSpiritualLaws", :integer
    t.column "hasExperienceFourSpiritualLaws", :integer
    t.column "confidenceFourSpiritualLaws", :integer
    t.column "isFamiliarLifeAtLarge", :integer
    t.column "hasExperienceLifeAtLarge", :integer
    t.column "confidenceLifeAtLarge", :integer
    t.column "isFamiliarPersonalTestimony", :integer
    t.column "hasExperiencePersonalTestimony", :integer
    t.column "confidencePersonalTestimony", :integer
    t.column "isFamiliarExplainingGospel", :integer
    t.column "hasExperienceExplainingGospel", :integer
    t.column "confidenceExplainingGospel", :integer
    t.column "isFamiliarSharingFaith", :integer
    t.column "hasExperienceSharingFaith", :integer
    t.column "confidenceSharingFaith", :integer
    t.column "isFamiliarHolySpiritBooklet", :integer
    t.column "hasExperienceHolySpiritBooklet", :integer
    t.column "confidenceHolySpiritBooklet", :integer
    t.column "isFamiliarFollowUp", :integer
    t.column "hasExperienceFollowUp", :integer
    t.column "confidenceFollowUp", :integer
    t.column "isFamiliarHelpGrowInFaith", :integer
    t.column "hasExperienceHelpGrowInFaith", :integer
    t.column "confidenceHelpGrowInFaith", :integer
    t.column "isFamiliarTrainShareFaith", :integer
    t.column "hasExperienceTrainShareFaith", :integer
    t.column "confidenceTrainShareFaith", :integer
    t.column "isFamiliarOtherReligions", :integer
    t.column "hasExperienceOtherReligions", :integer
    t.column "confidenceOtherReligions", :integer
    t.column "leadershipPositions", :text
    t.column "hasLedDiscipleshipGroup", :integer
    t.column "discipleshipGroupSize", :string, :limit => 50
    t.column "leadershipEvaluation", :text
    t.column "conversionMonth", :integer
    t.column "conversionYear", :integer
    t.column "memberChurchDenomination", :string, :limit => 75
    t.column "memberChurchDuration", :string, :limit => 50
    t.column "attendingChurchDenomination", :string, :limit => 50
    t.column "attendingChurchDuration", :string, :limit => 50
    t.column "attendingChurchInvolvement", :text
    t.column "quietTimeQuantity", :text
    t.column "quietTimeDescription", :text
    t.column "explanationOfSalvation", :text
    t.column "explanationOfSpiritFilled", :text
    t.column "hasInvolvementSpeakingTongues", :integer
    t.column "differenceIndwellingFilled", :text
    t.column "hasCrimeConviction", :integer
    t.column "crimeConvictionExplanation", :text
    t.column "hasDrugUse", :integer
    t.column "isTobaccoUser", :integer
    t.column "isWillingChangeHabits", :integer
    t.column "authorityResponseExplanation", :text
    t.column "alcoholUseFrequency", :text
    t.column "alcoholUseDecision", :text
    t.column "isWillingRefrainAlcohol", :integer
    t.column "unwillingRefrainAlcoholExplanation", :text
    t.column "drugUseExplanation", :text
    t.column "tobaccoUseExplanation", :text
    t.column "isWillingAbstainTobacco", :integer
    t.column "hasRequestedPhoneCall", :integer
    t.column "contactPhoneNumber", :string, :limit => 50
    t.column "contactBestTime", :string, :limit => 50
    t.column "contactTimeZone", :string, :limit => 50
    t.column "sexualInvolvementExplanation", :text
    t.column "hasSexualGuidelines", :integer
    t.column "sexualGuidelineExplanation", :text
    t.column "isCurrentlyDating", :integer
    t.column "currentlyDatingLocation", :text
    t.column "hasHomosexualInvolvement", :integer
    t.column "homosexualInvolvementExplanation", :text
    t.column "hasRecentPornographicInvolvement", :integer
    t.column "pornographicInvolvementMonth", :integer
    t.column "pornographicInvolvementYear", :integer
    t.column "pornographicInvolvementExplanation", :text
    t.column "hasRecentSexualImmorality", :integer
    t.column "sexualImmoralityMonth", :integer
    t.column "sexualImmoralityYear", :integer
    t.column "sexualImmoralityExplanation", :text
    t.column "hasOtherDateSinceImmorality", :integer
    t.column "singleImmoralityResultsExplanation", :text
    t.column "marriedImmoralityResultsExplanation", :text
    t.column "immoralityLifeChangeExplanation", :text
    t.column "immoralityCurrentStrugglesExplanation", :text
    t.column "additionalMoralComments", :text
    t.column "isAwareMustRaiseSupport", :integer
    t.column "isInDebt", :integer
    t.column "debtNature1", :string, :limit => 50
    t.column "debtTotal1", :string, :limit => 50
    t.column "debtMonthlyPayment1", :string, :limit => 50
    t.column "debtNature2", :string, :limit => 50
    t.column "debtTotal2", :string, :limit => 50
    t.column "debtMonthlyPayment2", :string, :limit => 50
    t.column "debtNature3", :string, :limit => 50
    t.column "debtTotal3", :string, :limit => 50
    t.column "debtMonthlyPayment3", :string, :limit => 50
    t.column "hasOtherFinancialResponsibility", :integer
    t.column "otherFinancialResponsibilityExplanation", :text
    t.column "debtPaymentPlan", :text
    t.column "debtPaymentTimeframe", :text
    t.column "developingPartnersExplanation", :text
    t.column "isWillingDevelopPartners", :integer
    t.column "unwillingDevelopPartnersExplanation", :text
    t.column "isCommittedDevelopPartners", :integer
    t.column "uncommittedDevelopPartnersExplanation", :text
    t.column "personalTestimonyGrowth", :text
    t.column "internshipParticipationExplanation", :text
    t.column "internshipObjectives", :text
    t.column "currentMinistryDescription", :text
    t.column "personalStrengthA", :text
    t.column "personalStrengthB", :text
    t.column "personalStrengthC", :text
    t.column "personalDevelopmentA", :text
    t.column "personalDevelopmentB", :text
    t.column "personalDevelopmentC", :text
    t.column "personalDescriptionA", :text
    t.column "personalDescriptionB", :text
    t.column "personalDescriptionC", :text
    t.column "familyRelationshipDescription", :text
    t.column "electronicSignature", :string, :limit => 90
    t.column "ssn", :string, :limit => 50
    t.column "fk_ssmUserID", :integer
    t.column "fk_SIPersonID", :integer
    t.column "isPaid", :boolean
    t.column "appFee", :float
    t.column "dateAppLastChanged", :datetime
    t.column "dateAppStarted", :datetime
    t.column "dateSubmitted", :datetime
    t.column "isSubmitted", :boolean
    t.column "appStatus", :string, :limit => 15
    t.column "assignedToProject", :integer
    t.column "finalProject", :float
    t.column "siYear", :string, :limit => 50
    t.column "submitDate", :datetime
    t.column "status", :string, :limit => 22
    t.column "appType", :string, :limit => 64
    t.column "locationA", :string, :limit => 50
    t.column "locationAExplanation", :string, :limit => 90
    t.column "locationB", :string, :limit => 50
    t.column "locationBExplanation", :string, :limit => 90
    t.column "locationC", :string, :limit => 50
    t.column "locationCExplanation", :string, :limit => 90
    t.column "availableMonth", :string, :limit => 2
    t.column "availableYear", :string, :limit => 4
    t.column "hasMinistryConflict", :integer
    t.column "ministryConflictExplanation", :text
    t.column "hasSpecificLocation", :integer
    t.column "specificLocationRecruiterName", :string, :limit => 50
    t.column "teamMembers", :text
    t.column "isDating", :integer
    t.column "datingLocation", :text
    t.column "hasCampusPartnership", :integer
    t.column "isDatingStint", :integer
    t.column "datingStintName", :text
    t.column "language1", :string, :limit => 50
    t.column "language1YearsStudied", :string, :limit => 20
    t.column "language1Fluency", :integer
    t.column "language2", :string, :limit => 50
    t.column "language2YearsStudied", :string, :limit => 20
    t.column "language2Fluency", :integer
  end

  create_table "hr_si_application_2003", :id => false, :force => true do |t|
    t.column "applicationID", :integer, :default => 0, :null => false
    t.column "locationA", :string, :limit => 50
    t.column "ministryTraining", :text
    t.column "evangelismAttitude", :text
    t.column "isEvangelismTrainable", :integer
    t.column "participationExplanation", :text
    t.column "isFamiliarFourSpiritualLaws", :integer
    t.column "hasExperienceFourSpiritualLaws", :integer
    t.column "confidenceFourSpiritualLaws", :integer
    t.column "isFamiliarLifeAtLarge", :integer
    t.column "hasExperienceLifeAtLarge", :integer
    t.column "confidenceLifeAtLarge", :integer
    t.column "isFamiliarPersonalTestimony", :integer
    t.column "hasExperiencePersonalTestimony", :integer
    t.column "confidencePersonalTestimony", :integer
    t.column "isFamiliarExplainingGospel", :integer
    t.column "hasExperienceExplainingGospel", :integer
    t.column "confidenceExplainingGospel", :integer
    t.column "isFamiliarSharingFaith", :integer
    t.column "hasExperienceSharingFaith", :integer
    t.column "confidenceSharingFaith", :integer
    t.column "isFamiliarHolySpiritBooklet", :integer
    t.column "hasExperienceHolySpiritBooklet", :integer
    t.column "confidenceHolySpiritBooklet", :integer
    t.column "isFamiliarFollowUp", :integer
    t.column "hasExperienceFollowUp", :integer
    t.column "confidenceFollowUp", :integer
    t.column "isFamiliarHelpGrowInFaith", :integer
    t.column "hasExperienceHelpGrowInFaith", :integer
    t.column "confidenceHelpGrowInFaith", :integer
    t.column "isFamiliarTrainShareFaith", :integer
    t.column "hasExperienceTrainShareFaith", :integer
    t.column "confidenceTrainShareFaith", :integer
    t.column "isFamiliarOtherReligions", :integer
    t.column "hasExperienceOtherReligions", :integer
    t.column "confidenceOtherReligions", :integer
    t.column "leadershipPositions", :text
    t.column "hasLedDiscipleshipGroup", :integer
    t.column "discipleshipGroupSize", :string, :limit => 50
    t.column "leadershipEvaluation", :text
    t.column "conversionMonth", :integer
    t.column "conversionYear", :integer
    t.column "memberChurchDenomination", :string, :limit => 50
    t.column "memberChurchDuration", :string, :limit => 50
    t.column "attendingChurchDenomination", :string, :limit => 50
    t.column "attendingChurchDuration", :string, :limit => 50
    t.column "attendingChurchInvolvement", :text
    t.column "quietTimeQuantity", :text
    t.column "quietTimeDescription", :text
    t.column "explanationOfSalvation", :text
    t.column "explanationOfSpiritFilled", :text
    t.column "hasInvolvementSpeakingTongues", :integer
    t.column "differenceIndwellingFilled", :text
    t.column "hasCrimeConviction", :integer
    t.column "crimeConvictionExplanation", :text
    t.column "hasDrugUse", :integer
    t.column "isTobaccoUser", :integer
    t.column "isWillingChangeHabits", :integer
    t.column "authorityResponseExplanation", :text
    t.column "alcoholUseFrequency", :text
    t.column "alcoholUseDecision", :text
    t.column "isWillingRefrainAlcohol", :integer
    t.column "unwillingRefrainAlcoholExplanation", :text
    t.column "drugUseExplanation", :text
    t.column "tobaccoUseExplanation", :text
    t.column "isWillingAbstainTobacco", :integer
    t.column "hasRequestedPhoneCall", :integer
    t.column "contactPhoneNumber", :string, :limit => 50
    t.column "contactBestTime", :string, :limit => 50
    t.column "contactTimeZone", :string, :limit => 50
    t.column "sexualInvolvementExplanation", :text
    t.column "hasSexualGuidelines", :integer
    t.column "sexualGuidelineExplanation", :text
    t.column "isCurrentlyDating", :integer
    t.column "currentlyDatingLocation", :text
    t.column "hasHomosexualInvolvement", :integer
    t.column "homosexualInvolvementExplanation", :text
    t.column "hasRecentPornographicInvolvement", :integer
    t.column "pornographicInvolvementMonth", :integer
    t.column "pornographicInvolvementYear", :integer
    t.column "pornographicInvolvementExplanation", :text
    t.column "hasRecentSexualImmorality", :integer
    t.column "sexualImmoralityMonth", :integer
    t.column "sexualImmoralityYear", :integer
    t.column "sexualImmoralityExplanation", :text
    t.column "hasOtherDateSinceImmorality", :integer
    t.column "singleImmoralityResultsExplanation", :text
    t.column "marriedImmoralityResultsExplanation", :text
    t.column "immoralityLifeChangeExplanation", :text
    t.column "immoralityCurrentStrugglesExplanation", :text
    t.column "additionalMoralComments", :text
    t.column "isAwareMustRaiseSupport", :integer
    t.column "isInDebt", :integer
    t.column "debtNature1", :string, :limit => 50
    t.column "debtTotal1", :string, :limit => 50
    t.column "debtMonthlyPayment1", :string, :limit => 50
    t.column "debtNature2", :string, :limit => 50
    t.column "debtTotal2", :string, :limit => 50
    t.column "debtMonthlyPayment2", :string, :limit => 50
    t.column "debtNature3", :string, :limit => 50
    t.column "debtTotal3", :string, :limit => 50
    t.column "debtMonthlyPayment3", :string, :limit => 50
    t.column "hasOtherFinancialResponsibility", :integer
    t.column "otherFinancialResponsibilityExplanation", :text
    t.column "debtPaymentPlan", :text
    t.column "debtPaymentTimeframe", :text
    t.column "developingPartnersExplanation", :text
    t.column "isWillingDevelopPartners", :integer
    t.column "unwillingDevelopPartnersExplanation", :text
    t.column "isCommittedDevelopPartners", :integer
    t.column "uncommittedDevelopPartnersExplanation", :text
    t.column "personalTestimonyGrowth", :text
    t.column "internshipParticipationExplanation", :text
    t.column "internshipObjectives", :text
    t.column "currentMinistryDescription", :text
    t.column "personalStrengthA", :text
    t.column "personalStrengthB", :text
    t.column "personalStrengthC", :text
    t.column "personalDevelopmentA", :text
    t.column "personalDevelopmentB", :text
    t.column "personalDevelopmentC", :text
    t.column "personalDescriptionA", :text
    t.column "personalDescriptionB", :text
    t.column "personalDescriptionC", :text
    t.column "familyRelationshipDescription", :text
    t.column "electronicSignature", :string, :limit => 90
    t.column "ssn", :string, :limit => 50
    t.column "fk_ssmUserID", :integer
    t.column "fk_SIPersonID", :string, :limit => 64
    t.column "isPaid", :boolean
    t.column "appFee", :float
    t.column "dateAppLastChanged", :datetime
    t.column "dateAppStarted", :datetime
    t.column "dateSubmitted", :datetime
    t.column "isSubmitted", :boolean
    t.column "appStatus", :string, :limit => 15
    t.column "assignedToProject", :integer
    t.column "finalProject", :float
    t.column "siYear", :string, :limit => 50
    t.column "submitDate", :datetime
    t.column "status", :string, :limit => 22
    t.column "appType", :string, :limit => 64
    t.column "locationAExplanation", :string, :limit => 90
    t.column "locationB", :string, :limit => 50
    t.column "locationBExplanation", :string, :limit => 90
    t.column "locationC", :string, :limit => 50
    t.column "locationCExplanation", :string, :limit => 90
    t.column "availableMonth", :string, :limit => 2
    t.column "availableYear", :string, :limit => 4
    t.column "hasMinistryConflict", :integer
    t.column "ministryConflictExplanation", :text
    t.column "hasSpecificLocation", :integer
    t.column "specificLocationRecruiterName", :string, :limit => 50
    t.column "teamMembers", :text
    t.column "isDating", :integer
    t.column "datingLocation", :text
    t.column "hasCampusPartnership", :integer
    t.column "isDatingStint", :integer
    t.column "datingStintName", :text
    t.column "language1", :string, :limit => 50
    t.column "language1YearsStudied", :string, :limit => 20
    t.column "language1Fluency", :integer
    t.column "language2", :string, :limit => 50
    t.column "language2YearsStudied", :string, :limit => 20
    t.column "language2Fluency", :integer
    t.column "previousMinistryExperience", :text
  end

  create_table "hr_si_application_2004", :id => false, :force => true do |t|
    t.column "applicationID", :integer, :default => 0, :null => false
    t.column "locationA", :string, :limit => 50
    t.column "ministryTraining", :text
    t.column "evangelismAttitude", :text
    t.column "isEvangelismTrainable", :integer
    t.column "participationExplanation", :text
    t.column "isFamiliarFourSpiritualLaws", :integer
    t.column "hasExperienceFourSpiritualLaws", :integer
    t.column "confidenceFourSpiritualLaws", :integer
    t.column "isFamiliarLifeAtLarge", :integer
    t.column "hasExperienceLifeAtLarge", :integer
    t.column "confidenceLifeAtLarge", :integer
    t.column "isFamiliarPersonalTestimony", :integer
    t.column "hasExperiencePersonalTestimony", :integer
    t.column "confidencePersonalTestimony", :integer
    t.column "isFamiliarExplainingGospel", :integer
    t.column "hasExperienceExplainingGospel", :integer
    t.column "confidenceExplainingGospel", :integer
    t.column "isFamiliarSharingFaith", :integer
    t.column "hasExperienceSharingFaith", :integer
    t.column "confidenceSharingFaith", :integer
    t.column "isFamiliarHolySpiritBooklet", :integer
    t.column "hasExperienceHolySpiritBooklet", :integer
    t.column "confidenceHolySpiritBooklet", :integer
    t.column "isFamiliarFollowUp", :integer
    t.column "hasExperienceFollowUp", :integer
    t.column "confidenceFollowUp", :integer
    t.column "isFamiliarHelpGrowInFaith", :integer
    t.column "hasExperienceHelpGrowInFaith", :integer
    t.column "confidenceHelpGrowInFaith", :integer
    t.column "isFamiliarTrainShareFaith", :integer
    t.column "hasExperienceTrainShareFaith", :integer
    t.column "confidenceTrainShareFaith", :integer
    t.column "isFamiliarOtherReligions", :integer
    t.column "hasExperienceOtherReligions", :integer
    t.column "confidenceOtherReligions", :integer
    t.column "leadershipPositions", :text
    t.column "hasLedDiscipleshipGroup", :integer
    t.column "discipleshipGroupSize", :string, :limit => 50
    t.column "leadershipEvaluation", :text
    t.column "conversionMonth", :integer
    t.column "conversionYear", :integer
    t.column "memberChurchDenomination", :string, :limit => 50
    t.column "memberChurchDuration", :string, :limit => 50
    t.column "attendingChurchDenomination", :string, :limit => 50
    t.column "attendingChurchDuration", :string, :limit => 50
    t.column "attendingChurchInvolvement", :text
    t.column "quietTimeQuantity", :text
    t.column "quietTimeDescription", :text
    t.column "explanationOfSalvation", :text
    t.column "explanationOfSpiritFilled", :text
    t.column "hasInvolvementSpeakingTongues", :integer
    t.column "differenceIndwellingFilled", :text
    t.column "hasCrimeConviction", :integer
    t.column "crimeConvictionExplanation", :text
    t.column "hasDrugUse", :integer
    t.column "isTobaccoUser", :integer
    t.column "isWillingChangeHabits", :integer
    t.column "authorityResponseExplanation", :text
    t.column "alcoholUseFrequency", :text
    t.column "alcoholUseDecision", :text
    t.column "isWillingRefrainAlcohol", :integer
    t.column "unwillingRefrainAlcoholExplanation", :text
    t.column "drugUseExplanation", :text
    t.column "tobaccoUseExplanation", :text
    t.column "isWillingAbstainTobacco", :integer
    t.column "hasRequestedPhoneCall", :integer
    t.column "contactPhoneNumber", :string, :limit => 50
    t.column "contactBestTime", :string, :limit => 50
    t.column "contactTimeZone", :string, :limit => 50
    t.column "sexualInvolvementExplanation", :text
    t.column "hasSexualGuidelines", :integer
    t.column "sexualGuidelineExplanation", :text
    t.column "isCurrentlyDating", :integer
    t.column "currentlyDatingLocation", :text
    t.column "hasHomosexualInvolvement", :integer
    t.column "homosexualInvolvementExplanation", :text
    t.column "hasRecentPornographicInvolvement", :integer
    t.column "pornographicInvolvementMonth", :integer
    t.column "pornographicInvolvementYear", :integer
    t.column "pornographicInvolvementExplanation", :text
    t.column "hasRecentSexualImmorality", :integer
    t.column "sexualImmoralityMonth", :integer
    t.column "sexualImmoralityYear", :integer
    t.column "sexualImmoralityExplanation", :text
    t.column "hasOtherDateSinceImmorality", :integer
    t.column "singleImmoralityResultsExplanation", :text
    t.column "marriedImmoralityResultsExplanation", :text
    t.column "immoralityLifeChangeExplanation", :text
    t.column "immoralityCurrentStrugglesExplanation", :text
    t.column "additionalMoralComments", :text
    t.column "isAwareMustRaiseSupport", :integer
    t.column "isInDebt", :integer
    t.column "debtNature1", :string, :limit => 50
    t.column "debtTotal1", :string, :limit => 50
    t.column "debtMonthlyPayment1", :string, :limit => 50
    t.column "debtNature2", :string, :limit => 50
    t.column "debtTotal2", :string, :limit => 50
    t.column "debtMonthlyPayment2", :string, :limit => 50
    t.column "debtNature3", :string, :limit => 50
    t.column "debtTotal3", :string, :limit => 50
    t.column "debtMonthlyPayment3", :string, :limit => 50
    t.column "hasOtherFinancialResponsibility", :integer
    t.column "otherFinancialResponsibilityExplanation", :text
    t.column "debtPaymentPlan", :text
    t.column "debtPaymentTimeframe", :text
    t.column "developingPartnersExplanation", :text
    t.column "isWillingDevelopPartners", :integer
    t.column "unwillingDevelopPartnersExplanation", :text
    t.column "isCommittedDevelopPartners", :integer
    t.column "uncommittedDevelopPartnersExplanation", :text
    t.column "personalTestimonyGrowth", :text
    t.column "internshipParticipationExplanation", :text
    t.column "internshipObjectives", :text
    t.column "currentMinistryDescription", :text
    t.column "personalStrengthA", :text
    t.column "personalStrengthB", :text
    t.column "personalStrengthC", :text
    t.column "personalDevelopmentA", :text
    t.column "personalDevelopmentB", :text
    t.column "personalDevelopmentC", :text
    t.column "personalDescriptionA", :text
    t.column "personalDescriptionB", :text
    t.column "personalDescriptionC", :text
    t.column "familyRelationshipDescription", :text
    t.column "electronicSignature", :string, :limit => 90
    t.column "ssn", :string, :limit => 50
    t.column "fk_ssmUserID", :integer
    t.column "fk_SIPersonID", :string, :limit => 64
    t.column "isPaid", :boolean
    t.column "appFee", :float
    t.column "dateAppLastChanged", :datetime
    t.column "dateAppStarted", :datetime
    t.column "dateSubmitted", :datetime
    t.column "isSubmitted", :boolean
    t.column "appStatus", :string, :limit => 15
    t.column "assignedToProject", :integer
    t.column "finalProject", :float
    t.column "siYear", :string, :limit => 50
    t.column "submitDate", :datetime
    t.column "status", :string, :limit => 22
    t.column "appType", :string, :limit => 64
    t.column "locationAExplanation", :string, :limit => 90
    t.column "locationB", :string, :limit => 50
    t.column "locationBExplanation", :string, :limit => 90
    t.column "locationC", :string, :limit => 50
    t.column "locationCExplanation", :string, :limit => 90
    t.column "availableMonth", :string, :limit => 2
    t.column "availableYear", :string, :limit => 4
    t.column "hasMinistryConflict", :integer
    t.column "ministryConflictExplanation", :text
    t.column "hasSpecificLocation", :integer
    t.column "specificLocationRecruiterName", :string, :limit => 50
    t.column "teamMembers", :text
    t.column "isDating", :integer
    t.column "datingLocation", :text
    t.column "hasCampusPartnership", :integer
    t.column "isDatingStint", :integer
    t.column "datingStintName", :text
    t.column "language1", :string, :limit => 50
    t.column "language1YearsStudied", :string, :limit => 20
    t.column "language1Fluency", :integer
    t.column "language2", :string, :limit => 50
    t.column "language2YearsStudied", :string, :limit => 20
    t.column "language2Fluency", :integer
    t.column "previousMinistryExperience", :text
  end

  create_table "hr_si_application_2005", :id => false, :force => true do |t|
    t.column "applicationID", :integer, :default => 0, :null => false
    t.column "locationA", :string, :limit => 50
    t.column "ministryTraining", :text
    t.column "evangelismAttitude", :text
    t.column "isEvangelismTrainable", :integer
    t.column "participationExplanation", :text
    t.column "isFamiliarFourSpiritualLaws", :integer
    t.column "hasExperienceFourSpiritualLaws", :integer
    t.column "confidenceFourSpiritualLaws", :integer
    t.column "isFamiliarLifeAtLarge", :integer
    t.column "hasExperienceLifeAtLarge", :integer
    t.column "confidenceLifeAtLarge", :integer
    t.column "isFamiliarPersonalTestimony", :integer
    t.column "hasExperiencePersonalTestimony", :integer
    t.column "confidencePersonalTestimony", :integer
    t.column "isFamiliarExplainingGospel", :integer
    t.column "hasExperienceExplainingGospel", :integer
    t.column "confidenceExplainingGospel", :integer
    t.column "isFamiliarSharingFaith", :integer
    t.column "hasExperienceSharingFaith", :integer
    t.column "confidenceSharingFaith", :integer
    t.column "isFamiliarHolySpiritBooklet", :integer
    t.column "hasExperienceHolySpiritBooklet", :integer
    t.column "confidenceHolySpiritBooklet", :integer
    t.column "isFamiliarFollowUp", :integer
    t.column "hasExperienceFollowUp", :integer
    t.column "confidenceFollowUp", :integer
    t.column "isFamiliarHelpGrowInFaith", :integer
    t.column "hasExperienceHelpGrowInFaith", :integer
    t.column "confidenceHelpGrowInFaith", :integer
    t.column "isFamiliarTrainShareFaith", :integer
    t.column "hasExperienceTrainShareFaith", :integer
    t.column "confidenceTrainShareFaith", :integer
    t.column "isFamiliarOtherReligions", :integer
    t.column "hasExperienceOtherReligions", :integer
    t.column "confidenceOtherReligions", :integer
    t.column "leadershipPositions", :text
    t.column "hasLedDiscipleshipGroup", :integer
    t.column "discipleshipGroupSize", :string, :limit => 50
    t.column "leadershipEvaluation", :text
    t.column "conversionMonth", :integer
    t.column "conversionYear", :integer
    t.column "memberChurchDenomination", :string, :limit => 75
    t.column "memberChurchDuration", :string, :limit => 50
    t.column "attendingChurchDenomination", :string, :limit => 50
    t.column "attendingChurchDuration", :string, :limit => 50
    t.column "attendingChurchInvolvement", :text
    t.column "quietTimeQuantity", :text
    t.column "quietTimeDescription", :text
    t.column "explanationOfSalvation", :text
    t.column "explanationOfSpiritFilled", :text
    t.column "hasInvolvementSpeakingTongues", :integer
    t.column "differenceIndwellingFilled", :text
    t.column "hasCrimeConviction", :integer
    t.column "crimeConvictionExplanation", :text
    t.column "hasDrugUse", :integer
    t.column "isTobaccoUser", :integer
    t.column "isWillingChangeHabits", :integer
    t.column "authorityResponseExplanation", :text
    t.column "alcoholUseFrequency", :text
    t.column "alcoholUseDecision", :text
    t.column "isWillingRefrainAlcohol", :integer
    t.column "unwillingRefrainAlcoholExplanation", :text
    t.column "drugUseExplanation", :text
    t.column "tobaccoUseExplanation", :text
    t.column "isWillingAbstainTobacco", :integer
    t.column "hasRequestedPhoneCall", :integer
    t.column "contactPhoneNumber", :string, :limit => 50
    t.column "contactBestTime", :string, :limit => 50
    t.column "contactTimeZone", :string, :limit => 50
    t.column "sexualInvolvementExplanation", :text
    t.column "hasSexualGuidelines", :integer
    t.column "sexualGuidelineExplanation", :text
    t.column "isCurrentlyDating", :integer
    t.column "currentlyDatingLocation", :text
    t.column "hasHomosexualInvolvement", :integer
    t.column "homosexualInvolvementExplanation", :text
    t.column "hasRecentPornographicInvolvement", :integer
    t.column "pornographicInvolvementMonth", :integer
    t.column "pornographicInvolvementYear", :integer
    t.column "pornographicInvolvementExplanation", :text
    t.column "hasRecentSexualImmorality", :integer
    t.column "sexualImmoralityMonth", :integer
    t.column "sexualImmoralityYear", :integer
    t.column "sexualImmoralityExplanation", :text
    t.column "hasOtherDateSinceImmorality", :integer
    t.column "singleImmoralityResultsExplanation", :text
    t.column "marriedImmoralityResultsExplanation", :text
    t.column "immoralityLifeChangeExplanation", :text
    t.column "immoralityCurrentStrugglesExplanation", :text
    t.column "additionalMoralComments", :text
    t.column "isAwareMustRaiseSupport", :integer
    t.column "isInDebt", :integer
    t.column "debtNature1", :string, :limit => 50
    t.column "debtTotal1", :string, :limit => 50
    t.column "debtMonthlyPayment1", :string, :limit => 50
    t.column "debtNature2", :string, :limit => 50
    t.column "debtTotal2", :string, :limit => 50
    t.column "debtMonthlyPayment2", :string, :limit => 50
    t.column "debtNature3", :string, :limit => 50
    t.column "debtTotal3", :string, :limit => 50
    t.column "debtMonthlyPayment3", :string, :limit => 50
    t.column "hasOtherFinancialResponsibility", :integer
    t.column "otherFinancialResponsibilityExplanation", :text
    t.column "debtPaymentPlan", :text
    t.column "debtPaymentTimeframe", :text
    t.column "developingPartnersExplanation", :text
    t.column "isWillingDevelopPartners", :integer
    t.column "unwillingDevelopPartnersExplanation", :text
    t.column "isCommittedDevelopPartners", :integer
    t.column "uncommittedDevelopPartnersExplanation", :text
    t.column "personalTestimonyGrowth", :text
    t.column "internshipParticipationExplanation", :text
    t.column "internshipObjectives", :text
    t.column "currentMinistryDescription", :text
    t.column "personalStrengthA", :text
    t.column "personalStrengthB", :text
    t.column "personalStrengthC", :text
    t.column "personalDevelopmentA", :text
    t.column "personalDevelopmentB", :text
    t.column "personalDevelopmentC", :text
    t.column "personalDescriptionA", :text
    t.column "personalDescriptionB", :text
    t.column "personalDescriptionC", :text
    t.column "familyRelationshipDescription", :text
    t.column "electronicSignature", :string, :limit => 90
    t.column "ssn", :string, :limit => 50
    t.column "fk_ssmUserID", :integer
    t.column "fk_SIPersonID", :string, :limit => 64
    t.column "isPaid", :boolean
    t.column "appFee", :float
    t.column "dateAppLastChanged", :datetime
    t.column "dateAppStarted", :datetime
    t.column "dateSubmitted", :datetime
    t.column "isSubmitted", :boolean
    t.column "appStatus", :string, :limit => 15
    t.column "assignedToProject", :integer
    t.column "finalProject", :float
    t.column "siYear", :string, :limit => 50
    t.column "submitDate", :datetime
    t.column "status", :string, :limit => 22
    t.column "appType", :string, :limit => 64
    t.column "locationAExplanation", :string, :limit => 90
    t.column "locationB", :string, :limit => 50
    t.column "locationBExplanation", :string, :limit => 90
    t.column "locationC", :string, :limit => 50
    t.column "locationCExplanation", :string, :limit => 90
    t.column "availableMonth", :string, :limit => 2
    t.column "availableYear", :string, :limit => 4
    t.column "hasMinistryConflict", :integer
    t.column "ministryConflictExplanation", :text
    t.column "hasSpecificLocation", :integer
    t.column "specificLocationRecruiterName", :string, :limit => 50
    t.column "teamMembers", :text
    t.column "isDating", :integer
    t.column "datingLocation", :text
    t.column "hasCampusPartnership", :integer
    t.column "isDatingStint", :integer
    t.column "datingStintName", :text
    t.column "language1", :string, :limit => 50
    t.column "language1YearsStudied", :string, :limit => 20
    t.column "language1Fluency", :integer
    t.column "language2", :string, :limit => 50
    t.column "language2YearsStudied", :string, :limit => 20
    t.column "language2Fluency", :integer
    t.column "previousMinistryExperience", :text
  end

  create_table "hr_si_application_2006", :id => false, :force => true do |t|
    t.column "applicationID", :integer, :default => 0, :null => false
    t.column "oldPrimaryKey", :string, :limit => 64
    t.column "previousMinistryExperience", :text
    t.column "ministryTraining", :text
    t.column "evangelismAttitude", :text
    t.column "isEvangelismTrainable", :integer
    t.column "participationExplanation", :text
    t.column "isFamiliarFourSpiritualLaws", :integer
    t.column "hasExperienceFourSpiritualLaws", :integer
    t.column "confidenceFourSpiritualLaws", :integer
    t.column "isFamiliarLifeAtLarge", :integer
    t.column "hasExperienceLifeAtLarge", :integer
    t.column "confidenceLifeAtLarge", :integer
    t.column "isFamiliarPersonalTestimony", :integer
    t.column "hasExperiencePersonalTestimony", :integer
    t.column "confidencePersonalTestimony", :integer
    t.column "isFamiliarExplainingGospel", :integer
    t.column "hasExperienceExplainingGospel", :integer
    t.column "confidenceExplainingGospel", :integer
    t.column "isFamiliarSharingFaith", :integer
    t.column "hasExperienceSharingFaith", :integer
    t.column "confidenceSharingFaith", :integer
    t.column "isFamiliarHolySpiritBooklet", :integer
    t.column "hasExperienceHolySpiritBooklet", :integer
    t.column "confidenceHolySpiritBooklet", :integer
    t.column "isFamiliarFollowUp", :integer
    t.column "hasExperienceFollowUp", :integer
    t.column "confidenceFollowUp", :integer
    t.column "isFamiliarHelpGrowInFaith", :integer
    t.column "hasExperienceHelpGrowInFaith", :integer
    t.column "confidenceHelpGrowInFaith", :integer
    t.column "isFamiliarTrainShareFaith", :integer
    t.column "hasExperienceTrainShareFaith", :integer
    t.column "confidenceTrainShareFaith", :integer
    t.column "isFamiliarOtherReligions", :integer
    t.column "hasExperienceOtherReligions", :integer
    t.column "confidenceOtherReligions", :integer
    t.column "leadershipPositions", :text
    t.column "hasLedDiscipleshipGroup", :integer
    t.column "discipleshipGroupSize", :string, :limit => 50
    t.column "leadershipEvaluation", :text
    t.column "conversionMonth", :integer
    t.column "conversionYear", :integer
    t.column "memberChurchDenomination", :string, :limit => 75
    t.column "memberChurchDuration", :string, :limit => 50
    t.column "attendingChurchDenomination", :string, :limit => 50
    t.column "attendingChurchDuration", :string, :limit => 50
    t.column "attendingChurchInvolvement", :text
    t.column "quietTimeQuantity", :text
    t.column "quietTimeDescription", :text
    t.column "explanationOfSalvation", :text
    t.column "explanationOfSpiritFilled", :text
    t.column "hasInvolvementSpeakingTongues", :integer
    t.column "differenceIndwellingFilled", :text
    t.column "hasCrimeConviction", :integer
    t.column "crimeConvictionExplanation", :text
    t.column "hasDrugUse", :integer
    t.column "isTobaccoUser", :integer
    t.column "isWillingChangeHabits", :integer
    t.column "authorityResponseExplanation", :text
    t.column "alcoholUseFrequency", :text
    t.column "alcoholUseDecision", :text
    t.column "isWillingRefrainAlcohol", :integer
    t.column "unwillingRefrainAlcoholExplanation", :text
    t.column "drugUseExplanation", :text
    t.column "tobaccoUseExplanation", :text
    t.column "isWillingAbstainTobacco", :integer
    t.column "hasRequestedPhoneCall", :integer
    t.column "contactPhoneNumber", :string, :limit => 50
    t.column "contactBestTime", :string, :limit => 50
    t.column "contactTimeZone", :string, :limit => 50
    t.column "sexualInvolvementExplanation", :text
    t.column "hasSexualGuidelines", :integer
    t.column "sexualGuidelineExplanation", :text
    t.column "isCurrentlyDating", :integer
    t.column "currentlyDatingLocation", :text
    t.column "hasHomosexualInvolvement", :integer
    t.column "homosexualInvolvementExplanation", :text
    t.column "hasRecentPornographicInvolvement", :integer
    t.column "pornographicInvolvementMonth", :integer
    t.column "pornographicInvolvementYear", :integer
    t.column "pornographicInvolvementExplanation", :text
    t.column "hasRecentSexualImmorality", :integer
    t.column "sexualImmoralityMonth", :integer
    t.column "sexualImmoralityYear", :integer
    t.column "sexualImmoralityExplanation", :text
    t.column "hasOtherDateSinceImmorality", :integer
    t.column "singleImmoralityResultsExplanation", :text
    t.column "marriedImmoralityResultsExplanation", :text
    t.column "immoralityLifeChangeExplanation", :text
    t.column "immoralityCurrentStrugglesExplanation", :text
    t.column "additionalMoralComments", :text
    t.column "isAwareMustRaiseSupport", :integer
    t.column "isInDebt", :integer
    t.column "debtNature1", :string, :limit => 50
    t.column "debtTotal1", :string, :limit => 50
    t.column "debtMonthlyPayment1", :string, :limit => 50
    t.column "debtNature2", :string, :limit => 50
    t.column "debtTotal2", :string, :limit => 50
    t.column "debtMonthlyPayment2", :string, :limit => 50
    t.column "debtNature3", :string, :limit => 50
    t.column "debtTotal3", :string, :limit => 50
    t.column "debtMonthlyPayment3", :string, :limit => 50
    t.column "hasOtherFinancialResponsibility", :integer
    t.column "otherFinancialResponsibilityExplanation", :text
    t.column "debtPaymentPlan", :text
    t.column "debtPaymentTimeframe", :text
    t.column "developingPartnersExplanation", :text
    t.column "isWillingDevelopPartners", :integer
    t.column "unwillingDevelopPartnersExplanation", :text
    t.column "isCommittedDevelopPartners", :integer
    t.column "uncommittedDevelopPartnersExplanation", :text
    t.column "personalTestimonyGrowth", :text
    t.column "internshipParticipationExplanation", :text
    t.column "internshipObjectives", :text
    t.column "currentMinistryDescription", :text
    t.column "personalStrengthA", :text
    t.column "personalStrengthB", :text
    t.column "personalStrengthC", :text
    t.column "personalDevelopmentA", :text
    t.column "personalDevelopmentB", :text
    t.column "personalDevelopmentC", :text
    t.column "personalDescriptionA", :text
    t.column "personalDescriptionB", :text
    t.column "personalDescriptionC", :text
    t.column "familyRelationshipDescription", :text
    t.column "electronicSignature", :string, :limit => 90
    t.column "ssn", :string, :limit => 50
    t.column "fk_ssmUserID", :integer
    t.column "fk_SIPersonID", :string, :limit => 50
    t.column "isPaid", :boolean
    t.column "appFee", :float
    t.column "dateAppLastChanged", :datetime
    t.column "dateAppStarted", :datetime
    t.column "dateSubmitted", :datetime
    t.column "isSubmitted", :boolean
    t.column "appStatus", :string, :limit => 15
    t.column "assignedToProject", :integer
    t.column "finalProject", :float
    t.column "siYear", :string, :limit => 50
    t.column "submitDate", :datetime
    t.column "status", :string, :limit => 22
    t.column "appType", :string, :limit => 64
    t.column "locationA", :string, :limit => 50
    t.column "locationAExplanation", :string, :limit => 90
    t.column "locationB", :string, :limit => 50
    t.column "locationBExplanation", :string, :limit => 90
    t.column "locationC", :string, :limit => 50
    t.column "locationCExplanation", :string, :limit => 90
    t.column "availableMonth", :string, :limit => 2
    t.column "availableYear", :string, :limit => 4
    t.column "hasMinistryConflict", :integer
    t.column "ministryConflictExplanation", :text
    t.column "hasSpecificLocation", :integer
    t.column "specificLocationRecruiterName", :string, :limit => 50
    t.column "teamMembers", :text
    t.column "isDating", :integer
    t.column "datingLocation", :text
    t.column "hasCampusPartnership", :integer
    t.column "isDatingStint", :integer
    t.column "datingStintName", :text
    t.column "language1", :string, :limit => 50
    t.column "language1YearsStudied", :string, :limit => 20
    t.column "language1Fluency", :integer
    t.column "language2", :string, :limit => 50
    t.column "language2YearsStudied", :string, :limit => 20
    t.column "language2Fluency", :integer
  end

  create_table "hr_si_payment", :id => false, :force => true do |t|
    t.column "paymentID", :integer, :default => 0, :null => false
    t.column "oldPrimaryKey", :string, :limit => 64
    t.column "paymentDate", :datetime
    t.column "debit", :float
    t.column "credit", :float
    t.column "type", :string, :limit => 80
    t.column "authCode", :string, :limit => 80
    t.column "businessUnit", :string, :limit => 50
    t.column "dept", :string, :limit => 50
    t.column "region", :string, :limit => 50
    t.column "project", :string, :limit => 50
    t.column "accountNo", :string, :limit => 80
    t.column "comment", :string
    t.column "posted", :string, :limit => 1
    t.column "postedDate", :datetime
    t.column "fk_ApplicationID", :string, :limit => 64
    t.column "paymentFor", :string, :limit => 50
  end

end
