/*
 * Created on Jul 6, 2004
 *
 * To change the template for this generated file go to
 * Window&gt;Preferences&gt;Java&gt;Code Generation&gt;Code and Comments
 */
package org.alt60m.hr.si.model.dbio;

import java.util.*;

import com.kenburcham.framework.dbio.DBIOEntity;

/**
 * @author justin.sabelko
 *
 * To change the template for this generated type comment go to
 * Window&gt;Preferences&gt;Java&gt;Code Generation&gt;Code and Comments
 */
public abstract class SIReference_Parent extends DBIOEntity {
	public abstract boolean persist();
	public boolean insert() {
		return super.insert();
	}
	public abstract boolean isPKEmpty();
	public abstract void localinit();
	/**
	 * get & set methods
	*/
	public abstract String getReferenceID();
	public abstract void setReferenceID(String referenceID);
	public abstract int getReferenceIDInt();
	public abstract void setReferenceIDInt(int referenceID);
	public abstract String getFormWorkflowStatus();
	public abstract void setFormWorkflowStatus(String formWorkflowStatus);
	public abstract Date getCreateDate();
	public abstract void setCreateDate(Date createDate);
	public abstract Date getLastChangedDate();
	public abstract void setLastChangedDate(Date lastChangedDate);
	public abstract String getLastChangedBy();
	public abstract void setLastChangedBy(String lastChangedBy);
	public abstract boolean getIsFormSubmitted();
	public abstract void setIsFormSubmitted(boolean isFormSubmitted);
	public abstract Date getFormSubmittedDate();
	public abstract void setFormSubmittedDate(Date formSubmittedDate);
	public abstract String getReferenceType();
	public abstract void setReferenceType(String referenceType);
	public abstract String getTitle();
	public abstract void setTitle(String title);
	public abstract String getFirstName();
	public abstract void setFirstName(String firstName);
	public abstract String getLastName();
	public abstract void setLastName(String lastName);
	public abstract boolean getIsStaff();
	public abstract void setIsStaff(boolean isStaff);
	public abstract String getStaffNumber();
	public abstract void setStaffNumber(String staffNumber);
	public abstract String getCurrentAddress1();
	public abstract void setCurrentAddress1(String currentAddress1);
	public abstract String getCurrentAddress2();
	public abstract void setCurrentAddress2(String currentAddress2);
	public abstract String getCurrentCity();
	public abstract void setCurrentCity(String currentCity);
	public abstract String getCurrentState();
	public abstract void setCurrentState(String currentState);
	public abstract String getCurrentZip();
	public abstract void setCurrentZip(String currentZip);
	public abstract String getCellPhone();
	public abstract void setCellPhone(String cellPhone);
	public abstract String getHomePhone();
	public abstract void setHomePhone(String homePhone);
	public abstract String getWorkPhone();
	public abstract void setWorkPhone(String workPhone);
	public abstract String getCurrentEmail();
	public abstract void setCurrentEmail(String currentEmail);
	public abstract String getHowKnown();
	public abstract void setHowKnown(String howKnown);
	public abstract String getHowLongKnown();
	public abstract void setHowLongKnown(String howLongKnown);
	public abstract int getHowWellKnown();
	public abstract void setHowWellKnown(int howWellKnown);
	public abstract int getHowWellComm();
	public abstract void setHowWellComm(int howWellComm);
	public abstract String getAppType();
	public abstract void setAppType(String appType);
	public abstract int get_rg1();
	public abstract void set_rg1(int _rg1);
	public abstract int get_rg2();
	public abstract void set_rg2(int _rg2);
	public abstract int get_rg3();
	public abstract void set_rg3(int _rg3);
	public abstract int get_rg4();
	public abstract void set_rg4(int _rg4);
	public abstract int get_rg5();
	public abstract void set_rg5(int _rg5);
	public abstract String get_rg1c();
	public abstract void set_rg1c(String _rg1c);
	public abstract String get_rg2c();
	public abstract void set_rg2c(String _rg2c);
	public abstract String get_rg3c();
	public abstract void set_rg3c(String _rg3c);
	public abstract String get_rg4c();
	public abstract void set_rg4c(String _rg4c);
	public abstract String get_rg5c();
	public abstract void set_rg5c(String _rg5c);
	public abstract String get_rg6();
	public abstract void set_rg6(String _rg6);
	public abstract boolean get_rg7();
	public abstract void set_rg7(boolean _rg7);
	public abstract String get_rg8();
	public abstract void set_rg8(String _rg8);
	public abstract String get_rg9();
	public abstract void set_rg9(String _rg9);
	public abstract int get_ro1();
	public abstract void set_ro1(int _ro1);
	public abstract int get_ro2();
	public abstract void set_ro2(int _ro2);
	public abstract int get_ro3();
	public abstract void set_ro3(int _ro3);
	public abstract int get_ro4();
	public abstract void set_ro4(int _ro4);
	public abstract int get_ro5();
	public abstract void set_ro5(int _ro5);
	public abstract int get_ro6();
	public abstract void set_ro6(int _ro6);
	public abstract int get_ro7();
	public abstract void set_ro7(int _ro7);
	public abstract String get_ro1c();
	public abstract void set_ro1c(String _ro1c);
	public abstract String get_ro2c();
	public abstract void set_ro2c(String _ro2c);
	public abstract String get_ro3c();
	public abstract void set_ro3c(String _ro3c);
	public abstract String get_ro4c();
	public abstract void set_ro4c(String _ro4c);
	public abstract String get_ro5c();
	public abstract void set_ro5c(String _ro5c);
	public abstract String get_ro6c();
	public abstract void set_ro6c(String _ro6c);
	public abstract String get_ro7c();
	public abstract void set_ro7c(String _ro7c);
	public abstract String get_ro8();
	public abstract void set_ro8(String _ro8);
	public abstract String get_ro9();
	public abstract void set_ro9(String _ro9);
	public abstract String get_ro10();
	public abstract void set_ro10(String _ro10);
	public abstract int get_dd1();
	public abstract void set_dd1(int _dd1);
	public abstract int get_dd2();
	public abstract void set_dd2(int _dd2);
	public abstract int get_dd3();
	public abstract void set_dd3(int _dd3);
	public abstract int get_dd4();
	public abstract void set_dd4(int _dd4);
	public abstract String get_dd1c();
	public abstract void set_dd1c(String _dd1c);
	public abstract String get_dd2c();
	public abstract void set_dd2c(String _dd2c);
	public abstract String get_dd3c();
	public abstract void set_dd3c(String _dd3c);
	public abstract String get_dd4c();
	public abstract void set_dd4c(String _dd4c);
	public abstract String get_dd5();
	public abstract void set_dd5(String _dd5);
	public abstract String get_dd6();
	public abstract void set_dd6(String _dd6);
	public abstract int get_if1();
	public abstract void set_if1(int _if1);
	public abstract int get_if2();
	public abstract void set_if2(int _if2);
	public abstract int get_if3();
	public abstract void set_if3(int _if3);
	public abstract int get_if4();
	public abstract void set_if4(int _if4);
	public abstract String get_if1c();
	public abstract void set_if1c(String _if1c);
	public abstract String get_if2c();
	public abstract void set_if2c(String _if2c);
	public abstract String get_if3c();
	public abstract void set_if3c(String _if3c);
	public abstract String get_if4c();
	public abstract void set_if4c(String _if4c);
	public abstract String get_if5();
	public abstract void set_if5(String _if5);
	public abstract String get_if6();
	public abstract void set_if6(String _if6);
	public abstract int get_ch1();
	public abstract void set_ch1(int _ch1);
	public abstract int get_ch2();
	public abstract void set_ch2(int _ch2);
	public abstract int get_ch3();
	public abstract void set_ch3(int _ch3);
	public abstract int get_ch4();
	public abstract void set_ch4(int _ch4);
	public abstract int get_ch5();
	public abstract void set_ch5(int _ch5);
	public abstract String get_ch1c();
	public abstract void set_ch1c(String _ch1c);
	public abstract String get_ch2c();
	public abstract void set_ch2c(String _ch2c);
	public abstract String get_ch3c();
	public abstract void set_ch3c(String _ch3c);
	public abstract String get_ch4c();
	public abstract void set_ch4c(String _ch4c);
	public abstract String get_ch5c();
	public abstract void set_ch5c(String _ch5c);
	public abstract String get_ch6();
	public abstract void set_ch6(String _ch6);
	public abstract String get_ch7();
	public abstract void set_ch7(String _ch7);
	public abstract String get_ch8();
	public abstract void set_ch8(String _ch8);
	public abstract int get_ew1();
	public abstract void set_ew1(int _ew1);
	public abstract int get_ew2();
	public abstract void set_ew2(int _ew2);
	public abstract int get_ew3();
	public abstract void set_ew3(int _ew3);
	public abstract int get_ew4();
	public abstract void set_ew4(int _ew4);
	public abstract int get_ew5();
	public abstract void set_ew5(int _ew5);
	public abstract String get_ew1c();
	public abstract void set_ew1c(String _ew1c);
	public abstract String get_ew2c();
	public abstract void set_ew2c(String _ew2c);
	public abstract String get_ew3c();
	public abstract void set_ew3c(String _ew3c);
	public abstract String get_ew4c();
	public abstract void set_ew4c(String _ew4c);
	public abstract String get_ew5c();
	public abstract void set_ew5c(String _ew5c);
	public abstract String get_ew6();
	public abstract void set_ew6(String _ew6);
	public abstract boolean get_ew7();
	public abstract void set_ew7(boolean _ew7);
	public abstract String get_ew8();
	public abstract void set_ew8(String _ew8);
	public abstract boolean get_ew9();
	public abstract void set_ew9(boolean _ew9);
	public abstract String get_ew10();
	public abstract void set_ew10(String _ew10);
	public abstract int get_ms1();
	public abstract void set_ms1(int _ms1);
	public abstract int get_ms2();
	public abstract void set_ms2(int _ms2);
	public abstract int get_ms3();
	public abstract void set_ms3(int _ms3);
	public abstract int get_ms4();
	public abstract void set_ms4(int _ms4);
	public abstract String get_ms1c();
	public abstract void set_ms1c(String _ms1c);
	public abstract String get_ms2c();
	public abstract void set_ms2c(String _ms2c);
	public abstract String get_ms3c();
	public abstract void set_ms3c(String _ms3c);
	public abstract String get_ms4c();
	public abstract void set_ms4c(String _ms4c);
	public abstract String get_ms5();
	public abstract void set_ms5(String _ms5);
	public abstract int get_ls1();
	public abstract void set_ls1(int _ls1);
	public abstract int get_ls2();
	public abstract void set_ls2(int _ls2);
	public abstract int get_ls3();
	public abstract void set_ls3(int _ls3);
	public abstract int get_ls4();
	public abstract void set_ls4(int _ls4);
	public abstract int get_ls5();
	public abstract void set_ls5(int _ls5);
	public abstract String get_ls1c();
	public abstract void set_ls1c(String _ls1c);
	public abstract String get_ls2c();
	public abstract void set_ls2c(String _ls2c);
	public abstract String get_ls3c();
	public abstract void set_ls3c(String _ls3c);
	public abstract String get_ls4c();
	public abstract void set_ls4c(String _ls4c);
	public abstract String get_ls5c();
	public abstract void set_ls5c(String _ls5c);
	public abstract String get_ls6();
	public abstract void set_ls6(String _ls6);
	public abstract String get_ls7();
	public abstract void set_ls7(String _ls7);
	public abstract String get_ls8();
	public abstract void set_ls8(String _ls8);
	public abstract String get_re1();
	public abstract void set_re1(String _re1);
	public abstract String get_re2();
	public abstract void set_re2(String _re2);
	public abstract String get_re3();
	public abstract void set_re3(String _re3);
	public abstract int get_re4();
	public abstract void set_re4(int _re4);
	public abstract String get_re5();
	public abstract void set_re5(String _re5);
	public abstract String getFk_SIApplicationID();
	public abstract void setFk_SIApplicationID(String fk_SIApplicationID);
	public abstract SIApplication getSIApplication();
	public abstract void setSIApplication(SIApplication application);
	public abstract String getFk_SIPersonID();
	public abstract void setFk_SIPersonID(String fk_SIPersonID);
	public abstract SIPerson getSIPerson();
	public abstract void setSIPerson(SIPerson person);
	public abstract void loadRelated();
	public abstract String loadWorkflowStatusText();
	// ***********************************************************************
	public abstract String encodeReferenceID();
	// Given an encoded referenceId, decodes it back to a form that can be used for query on referenceId field
	public abstract String decodeReferenceID(String encRefID);
	// used to submit a reference form for processing.
	public abstract String submitReference();
	// Send the "Reference Invitation" email to this reference.
	public abstract boolean sendEmailInvite(String serverName, SIPerson person);
	// Send the "Reference Complete" email to applicant and others.
	public abstract boolean sendEmailRefComplete();
	// Send the "Reference Reminder" email to this reference.
	public abstract boolean sendEmailReminder(String serverName);
	// Send the "Reference Thank You" email to this reference.
	public abstract boolean sendEmailThankYou();
	// for this reference, check to see if all required fields are filled in for the application form
	public abstract String checkAppRequiredFields();
}