class AlterOrdersTable < ActiveRecord::Migration
  def self.up
    rename_column("fsk_orders", "locationName", "location_name")
    remove_column("fsk_orders", "dateCreated")
    remove_column("fsk_orders", "dateUpdated")
    rename_column("fsk_orders", "contactFirstName", "contact_first_name")
    rename_column("fsk_orders", "contactLastName", "contact_last_name")
    rename_column("fsk_orders", "contactPhone", "contact_phone")
    rename_column("fsk_orders", "contactCell", "contact_cell")
    rename_column("fsk_orders", "contactEmail", "contact_email")
    rename_column("fsk_orders", "shipName", "ship_name")
    rename_column("fsk_orders", "shipAddress1", "ship_address1")
    rename_column("fsk_orders", "shipAddress2", "ship_address2")
    rename_column("fsk_orders", "shipCity", "ship_city")
    rename_column("fsk_orders", "shipState", "ship_state")
    rename_column("fsk_orders", "shipZip", "ship_zip")
    rename_column("fsk_orders", "shipPhone", "ship_phone")
    rename_column("fsk_orders", "totalKits", "total_kits")
    rename_column("fsk_orders", "businessUnit", "business_unit")
    rename_column("fsk_orders", "operatingUnit", "operating_unit")
    rename_column("fsk_orders", "deptId", "dept_id")
    rename_column("fsk_orders", "projectId", "project_id")
    rename_column("fsk_orders", "orderYear", "order_year")
  end

  def self.down
    rename_column("fsk_orders", "location_name", "locationName")
    rename_column("fsk_orders", "contact_first_name", "contactFirstName")
    rename_column("fsk_orders", "contact_last_name", "contactLastName")
    rename_column("fsk_orders", "contact_phone", "contactPhone")
    rename_column("fsk_orders", "contact_cell", "contactCell")
    rename_column("fsk_orders", "contact_email", "contactEmail")
    rename_column("fsk_orders", "ship_name", "shipName")
    rename_column("fsk_orders", "ship_address1", "shipAddress1")
    rename_column("fsk_orders", "ship_address2", "shipAddress2")
    rename_column("fsk_orders", "ship_city", "shipCity")
    rename_column("fsk_orders", "ship_state", "shipState")
    rename_column("fsk_orders", "ship_zip", "shipZip")
    rename_column("fsk_orders", "ship_phone", "shipPhone")
    rename_column("fsk_orders", "total_kits", "totalKits")
    rename_column("fsk_orders", "business_unit", "businessUnit")
    rename_column("fsk_orders", "operating_unit", "operatingUnit")
    rename_column("fsk_orders", "dept_id", "deptId")
    rename_column("fsk_orders", "project_id", "projectId")
    rename_column("fsk_orders", "order_year", "orderYear")
  end
end
