/* Generated by Together */

package org.alt60m.crs.util;

public class CRSUtils {

	public static String normalizeSSMUserNames(String email) {
		//System.out.println("Was: " + email);
		//System.out.println(email.substring(email.indexOf("@")));
		if (email.substring(email.indexOf("@")).equalsIgnoreCase("@uscm.org")) {
			//System.out.println("Is1: " +
			// email.substring(0,email.indexOf("@")));
			return email.substring(0, email.indexOf("@"));
		} else {
			//System.out.println("Is2: " + email);
			return email;
		}
	}
	/*
	 * public static String clear2hash(String clearText) throws
	 * NoSuchAlgorithmException {
	 * 
	 * java.security.MessageDigest md =
	 * java.security.MessageDigest.getInstance("MD5"); byte[] ba =
	 * md.digest(clearText.getBytes()); return new
	 * String(org.alt60m.util.Base64.encode(ba));
	 *  }
	 */
}