/* Generated by Together */

package org.alt60m.staffSite.profiles.dbio;

/** This exception is thrown when condition occurred */
public class MultipleProfilesFoundException extends Exception {
    /** Constructs an Exception without a message. */
    public MultipleProfilesFoundException() {
        super();
    }

    /**
     * Constructs an Exception with a detailed message.
     * @param Message The message associated with the exception.
     */
    public MultipleProfilesFoundException(String message) {
        super(message);
    }
}
