/* Generated by Together */

package org.alt60m.staffSite.profiles.dbio;


/** This exception is thrown when condition occurred */
public class ProfileManagementException extends Exception {
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/** Constructs an Exception without a message. */
    public ProfileManagementException() {
        super();
    }

    /**
     * Constructs an Exception with a detailed message.
     * @param Message The message associated with the exception.
     */
    public ProfileManagementException(String message) {
        super(message);
    }

	public ProfileManagementException(String message, Exception cause) {
		super(message, cause);
	}

	public ProfileManagementException(String message, Throwable cause) {
		super(message, cause);
	}

	public ProfileManagementException(Throwable cause) {
		super(cause);
	}
	
	
}
