/* Generated by Together */

package org.alt60m.staffSite.profiles.dbio;

import org.alt60m.security.dbio.manager.UserNotFoundException;

/** This exception is thrown when condition occurred */
public class ProfileNotFoundException extends Exception {
    /** Constructs an Exception without a message. */
    public ProfileNotFoundException() {
        super();
    }

    /**
     * Constructs an Exception with a detailed message.
     * @param Message The message associated with the exception.
     */
    public ProfileNotFoundException(String message) {
        super(message);
    }

	public ProfileNotFoundException(String message, Throwable cause) {
		super(message, cause);
	}
}
