/* Generated by Together */

package org.alt60m.staffSite.profiles.dbio;

/** This exception is thrown when condition occurred */
public class ProfileAlreadyExistsException extends Exception {
    /** Constructs an Exception without a message. */
    public ProfileAlreadyExistsException() {
        super();
    }

    /**
     * Constructs an Exception with a detailed message.
     * @param Message The message associated with the exception.
     */
    public ProfileAlreadyExistsException(String message) {
        super(message);
    }
}
