/* Generated by Together */

package org.alt60m.staffSite.profiles.dbio;

/** This exception is thrown when condition occurred */
public class ProfileManagementException extends Exception {
    /** Constructs an Exception without a message. */
    public ProfileManagementException() {
        super();
    }

    /**
     * Constructs an Exception with a detailed message.
     * @param Message The message associated with the exception.
     */
    public ProfileManagementException(String message) {
        super(message);
    }
}
