/* Generated by Together */

package org.alt60m.fsk;

/** This exception is thrown when condition occurred */
public class FskBrokerException extends Exception {
    /** Constructs an Exception without a message. */
    public FskBrokerException() {
        super();
    }

    /**
     * Constructs an Exception with a detailed message.
     * @param Message The message associated with the exception.
     */
    public FskBrokerException(String message) {
        super(message);
    }

    public FskBrokerException(Exception e) {
        super(e.toString());
    }
}
