CREATE TABLE linczone_contacts (
  ContactID int NOT NULL identity,
  EntryDate smalldatetime NULL default getDate(),
  FirstName varchar(120) default NULL,
  LastName varchar(120) default NULL,
  HomeAddress varchar(120) default NULL,
  City varchar(20) default NULL,
  State varchar(20) default NULL,
  Zip varchar(80) default NULL,
  Email varchar(120) default NULL,
  HighSchool varchar(120) default NULL,
  CampusName varchar(200) default NULL,
  CampusID varchar(80) default NULL,
  ReferrerFirstName varchar(120) default NULL,
  ReferrerLastName varchar(120) default NULL,
  ReferrerRelationship varchar(100) default NULL,
  ReferrerEmail varchar(200) default NULL,
  InfoCCC char(1) default 'F',
  InfoNav char(1) default 'F',
  InfoIV char(1) default 'F',
  InfoFCA char(1) default 'F',
  InfoBSU char(1) default 'F',
  InfoCACM char(1) default 'F',
  InfoEFCA char(1) default 'F',
  InfoGCM char(1) default 'F',
  InfoWesley char(1) default 'F',
  PRIMARY KEY  (ContactID)
);
