/* Generated by Together */

package org.alt60m.ministry.model;

import java.util.*;

public class ActivitySimple {

    class Status {
		public static final String ACTIVE = "AC";
		public static final String INACTIVE = "IN";
		public static final String KEYCONTACT= "KE";
		public static final String LAUNCHED = "LA";
		public static final String PIONEERING = "PI";
		public static final String TRANSFORMATIONAL = "TR";
    }

    private String status = new String();
    private String strategy = new String();

	public String getStatusFullName() {
		if (status.equalsIgnoreCase(Status.ACTIVE)) return "Active";
		if (status.equalsIgnoreCase(Status.INACTIVE)) return "Inactive";
		if (status.equalsIgnoreCase(Status.KEYCONTACT)) return "Key Contact";
		if (status.equalsIgnoreCase(Status.LAUNCHED)) return "Launched";
		if (status.equalsIgnoreCase(Status.PIONEERING)) return "Pioneering";
		if (status.equalsIgnoreCase(Status.TRANSFORMATIONAL)) return "Transformational";
        return "Unknown";
    }
	public String getStatus() {
		return status;
	}
	public void setStatus(String status) {
		this.status = status; 
	}
    public boolean isActive() {
		return (!Status.INACTIVE.equalsIgnoreCase(this.status));
    }
    public String getStrategyFullName() {
		return org.alt60m.ministry.Strategies.expandStrategy(getStrategy());
    }
	public String getStrategy() {
		return strategy; 
	}
	public void setStrategy(String strategy) {
		this.strategy = strategy; 
	}
	public TargetAreaSimple getTargetArea() {
		return targetArea; 
	}
	public void setTargetArea(TargetAreaSimple targetArea) {
		this.targetArea = targetArea;
 	}
    public String getActivityID(){
            return activityID;
    }
    public void setActivityID(String activityID){
            this.activityID = activityID;
    }
    public LocalLevelSimple getTeam(){
            return team;
    }
	public void setTeam(LocalLevelSimple team){
    	this.team = team;
	}

    private TargetAreaSimple targetArea;

	private LocalLevelSimple team;

    private String activityID = new String();
}
