/* Generated by Together */

package org.alt60m.ministry.model;
import java.util.*;

/**
 * @persistent 
 * @table ministry_address
 * @key-generator UUID
 * @cache-type none
 * @access shared
 */
public class Address {
	/**
	 * @primary-key
	 */
    private String addressID = new String();
    private Date startDate;
    private Date endDate;
    private String address1 = new String();
    private String address2 = new String();
    private String address3 = new String();
    private String address4 = new String();
    private String city = new String();
    private String state = new String();
    private String zip = new String();
    private String country = new String();

	public Date getStartDate() {
		return startDate; 
	}
	public void setStartDate(Date startDate) {
	    if (startDate != null) {
		Calendar cin = Calendar.getInstance();
		Calendar cout = Calendar.getInstance();
		cin.setTime(startDate);
		cout.clear();
		cout.set(cin.get(Calendar.YEAR), cin.get(Calendar.MONTH), cin.get(Calendar.DATE));
		this.startDate = cout.getTime();
	    } else {
		this.startDate = startDate;
	    }	    
	}
	public Date getEndDate() {
		return endDate; 
	}
	public void setEndDate(Date endDate) {
	    if (endDate != null) {
		Calendar cin = Calendar.getInstance();
		Calendar cout = Calendar.getInstance();
		cin.setTime(endDate);
		cout.clear();
		cout.set(cin.get(Calendar.YEAR), cin.get(Calendar.MONTH), cin.get(Calendar.DATE));
		this.endDate = cout.getTime();
	    } else {
		this.endDate = endDate;
	    }	    
	}
	public String getAddress1() {
		return address1; 
	}
	public void setAddress1(String address1) {
		this.address1 = address1; 
	}
	public String getAddress2() {
		return address2; 
	}
	public void setAddress2(String address2) {
		this.address2 = address2; 
	}
	public String getAddress3() {
		return address3; 
	}
	public void setAddress3(String address3) {
		this.address3 = address3; 
	}
	public String getAddress4() {
		return address4; 
	}
	public void setAddress4(String address4) {
		this.address4 = address4; 
	}
	public String getCity() {
		return city; 
	}
	public void setCity(String city) {
		this.city = city; 
	}
	public String getState() {
		return state; 
	}
	public void setState(String state) {
		this.state = state; 
	}
	public String getZip() {
		return zip; 
	}
	public void setZip(String zip) {
		this.zip = zip; 
	}
	public String getCountry() {
		return country; 
	}
	public void setCountry(String country) {
		this.country = country; 
	}

    public String getAddressID(){
            return addressID;
        }

    public void setAddressID(String addressID){
            this.addressID = addressID;
        }
}
