/* Generated by Together */

package org.alt60m.ministry.model;
import java.util.*;

/**
 * @persistent 
 * @table ministry_Authorization
 * @key-generator UUID
 * @cache-type none
 * @access shared
 */
public class Authorization {
	/**
	 * @primary-key
	 */
    private String authorizationID = new String();

    private Date authDate;
    private String role = new String();
    private String authorized = new String();
    private long sequence;

    private Staff authorizedBy;
    private Note authorizationNote;
	private ChangeRequest changeRequest;


	public Date getAuthDate() {
		return authDate; 
	}
	public void setAuthDate(Date authDate) {
	    if (authDate != null) {
		Calendar cin = Calendar.getInstance();
		Calendar cout = Calendar.getInstance();
		cin.setTime(authDate);
		cout.clear();
		cout.set(cin.get(Calendar.YEAR), cin.get(Calendar.MONTH), cin.get(Calendar.DATE));
		this.authDate = cout.getTime();
	    } else {
		this.authDate = authDate;
	    }	    
	}
	public String getRole() {
		return role; 
	}
	public void setRole(String role) {
		this.role = role; 
	}
	public String getAuthorized() {
		return authorized; 
	}
	public void setAuthorized(String authorized) {
		this.authorized = authorized; 
	}
	public long getSequence() {
		return sequence; 
	}
	public void setSequence(long sequence) {
		this.sequence = sequence; 
	}

    public String getAuthorizationID(){
            return authorizationID;
        }

    public void setAuthorizationID(String authorizationID){
            this.authorizationID = authorizationID;
        }

    public Staff getAuthorizedBy(){
            return authorizedBy;
        }

    public void setAuthorizedBy(Staff authorizedBy){
            this.authorizedBy = authorizedBy;
        }

    public void assocAuthorizedBy(Staff authorizedBy){
            this.authorizedBy = authorizedBy;
        }

    public Note getAuthorizationNote(){
            return authorizationNote;
        }

    public void setAuthorizationNote(Note authorizationNote){
            this.authorizationNote = authorizationNote;
        }

    public void assocAuthorizationNote(Note authorizationNote){
            this.authorizationNote = authorizationNote;
        }

    public ChangeRequest getChangeRequest(){
            return changeRequest;
        }

    public void setChangeRequest(ChangeRequest changeRequest){
            this.changeRequest = changeRequest;
        }
}
