/* Generated by Together */

package org.alt60m.ministry.model;
import java.util.*;

/**
 * @persistent 
 * @table ministry_Dependent
 * @key-generator UUID
 * @cache-type none
 * @access shared
 */
public class Dependent {
	/**
	 * @primary-key
	 */
    private String dependentID = new String();
    private String firstName = new String();
    private String middleName = new String();
    private String lastName = new String();
    private Date birthDate;
    private String gender = new String();
	public String getFirstName() {
		return firstName; 
	}
	public void setFirstName(String firstName) {
		this.firstName = firstName; 
	}
	public String getMiddleName() {
		return middleName; 
	}
	public void setMiddleName(String middleName) {
		this.middleName = middleName; 
	}
	public String getLastName() {
		return lastName; 
	}
	public void setLastName(String lastName) {
		this.lastName = lastName; 
	}
	public Date getBirthDate() {
		return birthDate; 
	}
	public void setBirthDate(Date birthDate) {
	    if (birthDate != null) {
		Calendar cin = Calendar.getInstance();
		Calendar cout = Calendar.getInstance();
		cin.setTime(birthDate);
		cout.clear();
		cout.set(cin.get(Calendar.YEAR), cin.get(Calendar.MONTH), cin.get(Calendar.DATE));
		this.birthDate = cout.getTime();
	    } else {
		this.birthDate = birthDate;
	    }	    
	}
	public String getGender() {
		return gender; 
	}
	public void setGender(String gender) {
		this.gender = gender; 
	}


    public String getDependentID(){
            return dependentID;
        }

    public void setDependentID(String dependentID){
            this.dependentID = dependentID;
        }

    /**
     * @shapeType AssociationLink 
     * @undirected
     * @clientCardinality 0..n
     * @clientRole dependents
     * @supplierCardinality 0..n
     * @supplierRole parent
     * @label dependents
     */
    /*# private Staff dependents; */
}
