/* Generated by Together */

package org.alt60m.ministry.model;
import java.util.Date;

/**
 * @persistent 
 * @table ministry_fieldchange
 * @key-generator UUID
 * @cache-type none
 * @access shared
 */
public class FieldChange {

    public FieldChange() {}
    public FieldChange(String field, String oldValue, String newValue) {
        this.field = field;
        this.oldValue = oldValue;
        this.newValue = newValue;
    }

    /**
	 * @primary-key
	 */
    private String fieldChangeID = new String();

    private String field = new String();
    private String oldValue = new String();
    private String newValue = new String();
	private ChangeRequest changeRequest;

    public String getField() {
	return field; 
	}
	public void setField(String field) {
		this.field = field; 
	}
	public String getOldValue() {
		return oldValue; 
	}
	public void setOldValue(String oldValue) {
		this.oldValue = oldValue; 
	}
	public String getNewValue() {
		return newValue; 
	}
	public void setNewValue(String newValue) {
		this.newValue = newValue; 
	}

    public String getFieldChangeID(){
            return fieldChangeID;
        }

    public void setFieldChangeID(String fieldChangeID){
            this.fieldChangeID = fieldChangeID;
        }

    public ChangeRequest getChangeRequest(){
            return changeRequest;
        }

    public void setChangeRequest(ChangeRequest changeRequest){
            this.changeRequest = changeRequest;
        }
}
