/* Generated by Together */

package org.alt60m.ministry.model;

import java.util.*;

/**
 * @persistent 
 * @table ministry_locallevel
 * @key-generator UUID
 * @cache-type none
 * @access shared
 */
public class LocalLevel {

	/**
	 * @primary-key
	 */
    private String teamID = new String();  // dummy
    private String lane = new String();

	public String getLane() {
		return lane; 
	}
	public void setLane(String lane) {
		this.lane = lane; 
	}
    /**
     * @associates <{org.alt60m.ministry.model.Activity}>
     * @field-type org.alt60m.ministry.model.Activity
     * @many-table ministry_activity
     * @many-key fk_teamID
     */
  	private Collection activities = new Vector();
    private String address1 = new String();
    private String address2 = new String();
    private String city = new String();
    private String country = new String();
    private String email = new String();
    private String fax = new String();

    /**
    * @sql-type char[TF]
    */
    private boolean isActive;
    private String lane1 = new String();

    /**
     * @associates <{Staff}>
     * @field-type <{Staff}>
     * @many-key fk_teamID
     */
    private Collection members = new Vector();
    private String name = new String();
    private String note = new String();
    private String phone = new String();
    private String region = new String();
    private Date startDate;
    private String state = new String();
    private Date stopDate;

	/**
	 * @primary-key
	 */
    private String teamID1 = new String();
    private String url = new String();
    private String zip = new String();
    private String address = new String();
    private String address3 = new String();
    private String city1 = new String();
    private String country1 = new String();
    private String email1 = new String();
    private String fax1 = new String();

    /**
    * @sql-type char[TF]
    */
    private boolean isActive1;
    private String lane2 = new String();

    /**
     * @associates <{Staff}>
     * @field-type <{Staff}>
     * @many-key fk_teamID
     */
    private Collection members1 = new Vector();
    private String name1 = new String();
    private String note1 = new String();
    private String phone1 = new String();
    private String region1 = new String();
    private Date startDate1;
    private String state1 = new String();
    private Date stopDate1;

	/**
	 * @primary-key
	 */
    private String teamID2 = new String();
    private String url1 = new String();
    private String zip1 = new String();

    public Collection getActivities(){
            return activities;
        }

    public void setActivities(Collection activities){
            this.activities = activities;
        }

	public SortedSet getSortedActivities() {
		Vector acts = new Vector();
		acts.addAll(this.activities);
		/*Vector tmp = new Vector(this.activities); */
		Activity a, b;
		TargetArea ta1, ta2;
		SortedSet activitySet = new TreeSet(new ActivityComparator());
		for (int i = 0; i < acts.size(); i++) {
			a = (Activity)acts.get(i);
			if(a.getTargetArea() != null) {
				ta1 = a.getTargetArea();
				for(int j = 0; j < acts.size(); j++) {
					b = (Activity)acts.get(j);
					if(b.getTargetArea() != null) {
						ta2 = b.getTargetArea();
						if(ta1.getName().compareToIgnoreCase(ta2.getName()) == 0)
							if(a.getPeriodEnd() == null)
								if(b.getPeriodEnd() == null)
									if(a.getPeriodBegin().compareTo(b.getPeriodBegin()) < 0)
										activitySet.add(b);
									else activitySet.add(a);
								else activitySet.add(a);
							else if(b.getPeriodEnd() == null)
								if(a.getPeriodBegin().compareTo(b.getPeriodBegin()) < 0)
									activitySet.add(b);
								else activitySet.add(a);
							else if(a.getPeriodEnd().compareTo(b.getPeriodEnd()) < 0)
								activitySet.add(b);
							else
								activitySet.add(a);
						else
							activitySet.add(a);
					}
				}
			}
		}
		return activitySet;
		/*SortedSet activitySet = new TreeSet(new ActivityComparator());
		activitySet.addAll(activities);
		return activitySet;*/
	}


    public void assocActivity(Activity activity) {
		if(!this.activities.contains(activity)) {
            this.activities.add(activity);
        }
        activity.setTeam(this);
    }
    public void dissocActivity(Activity activity) {
		this.activities.remove(activity);
        activity.setTeam(null);
    }

	public String getAddress() {
		return address; 
	}

	public void setAddress(String address) {
		this.address = address; 
	}

	public String getAddress3() {
		return address3; 
	}

	public void setAddress3(String address3) {
		this.address3 = address3; 
	}

	public String getCity1() {
		return city1; 
	}

	public void setCity1(String city1) {
		this.city1 = city1; 
	}

	public String getCountry1() {
		return country1; 
	}

	public void setCountry1(String country1) {
		this.country1 = country1; 
	}

	public String getEmail1() {
		return email1; 
	}

	public void setEmail1(String email1) {
		this.email1 = email1; 
	}

	public String getFax1() {
		return fax1; 
	}

	public void setFax1(String fax1) {
		this.fax1 = fax1; 
	}

	public boolean getIsActive1() {
		return isActive1; 
	}

	public void setIsActive1(boolean isActive1) {
		this.isActive1 = isActive1; 
	}

	public String getLane2() {
		return lane2; 
	}

	public void setLane2(String lane2) {
		this.lane2 = lane2; 
	}

    public Collection getMembers1(){
            return members1;
        }

	public String getName1() {
		return name1; 
	}

	public void setName1(String name1) {
		this.name1 = name1; 
	}

	public String getNote1() {
		return note1; 
	}

	public void setNote1(String note1) {
		this.note1 = note1; 
	}

	public String getPhone1() {
		return phone1; 
	}

	public void setPhone1(String phone1) {
		this.phone1 = phone1; 
	}

	public String getRegion1() {
		return region1; 
	}

	public void setRegion1(String region1) {
		this.region1 = region1; 
	}

	public Date getStartDate1() {
		return startDate1; 
	}

	public void setStartDate1(Date startDate1) {
	    if (startDate1 != null) {
		Calendar cin = Calendar.getInstance();
		Calendar cout = Calendar.getInstance();
		cin.setTime(startDate1);
		cout.clear();
		cout.set(cin.get(Calendar.YEAR), cin.get(Calendar.MONTH), cin.get(Calendar.DATE));
		this.startDate1 = cout.getTime();
	    } else {
		this.startDate1 = startDate1;
	    }	    
	}

	public String getState1() {
		return state1; 
	}

	public void setState1(String state1) {
		this.state1 = state1; 
	}

	public Date getStopDate1() {
		return stopDate1; 
	}

	public void setStopDate1(Date stopDate1) {
	    if (stopDate1 != null) {
		Calendar cin = Calendar.getInstance();
		Calendar cout = Calendar.getInstance();
		cin.setTime(stopDate1);
		cout.clear();
		cout.set(cin.get(Calendar.YEAR), cin.get(Calendar.MONTH), cin.get(Calendar.DATE));
		this.stopDate1 = cout.getTime();
	    } else {
		this.stopDate1 = stopDate1;
	    }	    
	}

    public String getTeamID2(){
            return teamID2;
        }

    public void setTeamID2(String teamID2){
            this.teamID2 = teamID2;
        }

	public String getUrl1() {
		return url1; 
	}

	public void setUrl1(String url1) {
		this.url1 = url1; 
	}

	public String getZip1() {
		return zip1; 
	}

	public void setZip1(String zip1) {
		this.zip1 = zip1; 
	}

    public void addMembers(Staff staff) {
		members.add(staff);
//        staff.getMembership().add(this);
    }

	public String getAddress1() {
		return address1; 
	}

	public String getAddress2() {
		return address2; 
	}

	public String getCity() {
		return city; 
	}

	public String getCountry() {
		return country; 
	}

	public String getEmail() {
		return email; 
	}

	public String getFax() {
		return fax; 
	}

	public boolean getIsActive() {
		return isActive; 
	}

	public String getLane1() {
		return lane; 
	}

    public Collection getMembers(){
            return members;
        }
	public void setMembers(Collection members) {
		this.members = members;
	}
	public String getName() {
		return name; 
	}

	public String getNote() {
		return note; 
	}

	public String getPhone() {
		return phone; 
	}

	public String getRegion() {
		return region; 
	}

	public Date getStartDate() {
		return startDate; 
	}

	public String getState() {
		return state; 
	}

	public Date getStopDate() {
		return stopDate; 
	}

    public String getTeamID(){
            return teamID;
        }

	public String getUrl() {
		return url; 
	}

	public String getZip() {
		return zip; 
	}

	public void setAddress1(String address1) {
		this.address1 = address1; 
	}

	public void setAddress2(String address2) {
		this.address2 = address2; 
	}

	public void setCity(String city) {
		this.city = city; 
	}

	public void setCountry(String country) {
		this.country = country; 
	}

	public void setEmail(String email) {
		this.email = email; 
	}

	public void setFax(String fax) {
		this.fax = fax; 
	}

	public void setIsActive(boolean isActive) {
		this.isActive = isActive; 
	}

	public void setLane1(String lane) {
		this.lane = lane; 
	}

	public void setName(String name) {
		this.name = name; 
	}

	public void setNote(String note) {
		this.note = note; 
	}

	public void setPhone(String phone) {
		this.phone = phone; 
	}

	public void setRegion(String region) {
		this.region = region; 
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate; 
	}

	public void setState(String state) {
		this.state = state; 
	}

	public void setStopDate(Date stopDate) {
		this.stopDate = stopDate; 
	}

    public void setTeamID(String teamID){
            this.teamID = teamID;
        }

	public void setUrl(String url) {
		this.url = url; 
	}

	public void setZip(String zip) {
		this.zip = zip; 
	}

 //   public String getTeamID(){
  //          return teamID;
  //      }

  //  public void setTeamID(String teamID){
  //          this.teamID = teamID;
  //      }


}
