/* Generated by Together */

package org.alt60m.ministry.model;
import java.util.*;
import java.util.Date;
import java.util.Collection;
import java.util.Vector;

/**
 * @persistent 
 * @table ministry_noncccmin
 * @key-generator UUID
 * @cache-type none
 * @access shared
 */
public class NonCccMin {
    /**
	 * @primary-key
	 */
    private String nonCccMinID = new String();

    /**
     * @field-type org.alt60m.ministry.model.TargetArea
     * @many-table ministry_assoc_otherministries
     */
    private Collection otherMinistries = new Vector();

    private String ministry = new String();
    private String firstName = new String();
    private String lastName = new String();
    private String address1 = new String();
    private String address2 = new String();
    private String city = new String();
    private String state = new String();
    private String zip = new String();
    private String country = new String();
    private String homePhone = new String();
    private String workPhone = new String();
    private String mobilePhone = new String();
    private String email = new String();
    private String url = new String();
    private String pager = new String();
    private String fax = new String();
    private String note = new String();
	public String getMinistry() {
		return ministry; 
	}
	public void setMinistry(String ministry) {
		this.ministry = ministry; 
	}
	public String getFirstName() {
		return firstName; 
	}
	public void setFirstName(String firstName) {
		this.firstName = firstName; 
	}
	public String getLastName() {
		return lastName; 
	}
	public void setLastName(String lastName) {
		this.lastName = lastName; 
	}
	public String getAddress1() {
		return address1; 
	}
	public void setAddress1(String address1) {
		this.address1 = address1; 
	}
	public String getAddress2() {
		return address2; 
	}
	public void setAddress2(String address2) {
		this.address2 = address2; 
	}
	public String getCity() {
		return city; 
	}
	public void setCity(String city) {
		this.city = city; 
	}
	public String getState() {
		return state; 
	}
	public void setState(String state) {
		this.state = state; 
	}
	public String getZip() {
		return zip; 
	}
	public void setZip(String zip) {
		this.zip = zip; 
	}
	public String getCountry() {
		return country; 
	}
	public void setCountry(String country) {
		this.country = country; 
	}
	public String getHomePhone() {
		return homePhone; 
	}
	public void setHomePhone(String homePhone) {
		this.homePhone = homePhone; 
	}
	public String getWorkPhone() {
		return workPhone; 
	}
	public void setWorkPhone(String workPhone) {
		this.workPhone = workPhone; 
	}
	public String getMobilePhone() {
		return mobilePhone; 
	}
	public void setMobilePhone(String mobilePhone) {
		this.mobilePhone = mobilePhone; 
	}
	public String getEmail() {
		return email; 
	}
	public void setEmail(String email) {
		this.email = email; 
	}
	public String getUrl() {
		return url; 
	}
	public void setUrl(String url) {
		this.url = url; 
	}
	public String getPager() {
		return pager; 
	}
	public void setPager(String pager) {
		this.pager = pager; 
	}
	public String getFax() {
		return fax; 
	}
	public void setFax(String fax) {
		this.fax = fax; 
	}
	public String getNote() {
		return note; 
	}
	public void setNote(String note) {
		this.note = note; 
	}

    public String getNonCccMinID(){
            return nonCccMinID;
        }

    public void setNonCccMinID(String nonCccMinID){
            this.nonCccMinID = nonCccMinID;
        }

    public Collection getOtherMinistries(){
            return otherMinistries;
        }

    public void setOtherMinistries(Collection otherMinistries){
            this.otherMinistries = otherMinistries;
        }
    public void addOtherMinistry(TargetArea targetArea) {
		this.otherMinistries.add(targetArea);
    }

	public void removeOtherMinistry(TargetArea targetArea)
	{	Collection tempmin = new Vector();
		Iterator imin = otherMinistries.iterator();
		while(imin.hasNext())
		{	TargetArea ta = (TargetArea)imin.next();
			if(!ta.getTargetAreaID().equals(targetArea.getTargetAreaID()))  {
				tempmin.add(ta);
			}
		}
		setOtherMinistries(tempmin);
	}
}