/* Generated by Together */

package org.alt60m.ministry.model;
import java.util.*;

/**
 * @persistent 
 * @table ministry_Note
 * @key-generator UUID
 * @cache-type none
 * @access shared
 */
public class Note {
	/**
	 * @primary-key
	 */
    private String noteID = new String();
    private Date dateEntered;
    private String title = new String();
    private String note = new String();

	private Staff resignationLetter;
    private Staff loaNote;

    public Date getDateEntered() {
		return dateEntered; 
	}
	public void setDateEntered(Date dateEntered) {
	    if (dateEntered != null) {
		Calendar cin = Calendar.getInstance();
		Calendar cout = Calendar.getInstance();
		cin.setTime(dateEntered);
		cout.clear();
		cout.set(cin.get(Calendar.YEAR), cin.get(Calendar.MONTH), cin.get(Calendar.DATE));
		this.dateEntered = cout.getTime();
	    } else {
		this.dateEntered = dateEntered;
	    }	    
	}
	public String getTitle() {
		return title; 
	}
	public void setTitle(String title) {
		this.title = title; 
	}
	public String getNote() {
		return note; 
	}
	public void setNote(String note) {
		this.note = note; 
	}

    public String getNoteID(){
            return noteID;
        }

    public void setNoteID(String noteID){
            this.noteID = noteID;
        }
    public Staff getLoaNote() {
        return this.loaNote;
    }
    public void setLoaNote(Staff loaNote) {
        this.loaNote = loaNote;
    }
    public Staff getResignationLetter() {
		return this.resignationLetter;
    }
    public void setResignationLetter(Staff staff) {
		this.resignationLetter = staff;
    }

}
