/* Generated by Together */

package org.alt60m.ministry.model;

/**
 * @persistent 
 * @table ministry_regionalteam
 * @key-generator UUID
 * @cache-type none
 * @access shared
 * @identity teamID
 */
public class RegionalTeam {
	/**
	 * @primary-key
	 */
 	private String teamID = new String(); // dummy -- calls superclass get/setTeamID()


    private String no = new String();
    private String abbrv = new String();
    private String address1 = new String();
    private String address2 = new String();
    private String country = new String();
    private String city = new String();
    private String email = new String();
    private String fax = new String();
    private String region = new String();
    private String state = new String();

	/**
	 * @primary-key
	 */
    private String teamID1 = new String();
    private String url = new String();
    private String zip = new String();
    private String phone = new String();
    private String note = new String();
    private String name = new String();

	public String getNo() {
		return no; 
	}
	public void setNo(String no) {
		this.no = no; 
	}
	public String getAbbrv() {
		return abbrv; 
	}
	public void setAbbrv(String abbrv) {
		this.abbrv = abbrv; 
	}

	public void setFax(String fax) {
		this.fax = fax; 
	}

	public String getCountry() {
		return country; 
	}

	public String getUrl() {
		return url; 
	}

	public String getEmail() {
		return email; 
	}

	public void setAddress1(String address1) {
		this.address1 = address1; 
	}

	public String getCity() {
		return city; 
	}

	public String getNote() {
		return note; 
	}

	public String getAddress2() {
		return address2; 
	}

	public String getFax() {
		return fax; 
	}

	public String getName() {
		return name; 
	}

	public void setAddress2(String address2) {
		this.address2 = address2; 
	}

	public void setCountry(String country) {
		this.country = country; 
	}

	public void setEmail(String email) {
		this.email = email; 
	}

	public String getPhone() {
		return phone; 
	}

	public String getRegion() {
		return region; 
	}

	public String getState() {
		return state;
	}
    public String getTeamID(){
            return teamID;
        }

	public void setCity(String city) {
		this.city = city; 
	}

	public String getZip() {
		return zip; 
	}

	public String getAddress1() {
		return address1; 
	}

	public void setName(String name) {
		this.name = name; 
	}

	public void setNote(String note) {
		this.note = note; 
	}

	public void setPhone(String phone) {
		this.phone = phone; 
	}

	public void setRegion(String region) {
		this.region = region; 
	}

	public void setState(String state) {
		this.state = state; 
	}

    public void setTeamID(String teamID){
            this.teamID = teamID;
        }

	public void setUrl(String url) {
		this.url = url; 
	}

	public void setZip(String zip) {
		this.zip = zip; 
	}
}
