/* Generated by Together */

package org.alt60m.ministry.model;

/**
 * @persistent 
 * @table ministry_staffchangerequest
 * @key-generator UUID
 * @cache-type none
 * @access shared
 */
public class StaffChangeRequest extends ChangeRequest {

    /**
     *  Constant for a type of change, this is used both for the 'changeType' field
     *  in the Change Request table as well as many places through these objects.
     *  <b>NOTE:</b> A copy of these constants exists in the /CampusHR/formConfirm.jsp
     *  file, because these constants cannot be accessed from a JSP.
     */
    public static final String ADDRESS_CHANGE = "Address Change";
	
    /**
     *  Constant for a type of change, this is used both for the 'changeType' field
     *  in the Change Request table as well as many places through these objects.
     *  <b>NOTE:</b> A copy of these constants exists in the /CampusHR/formConfirm.jsp
     *  file, because these constants cannot be accessed from a JSP.
     */
    public static final String MARITAL_STATUS_CHANGE = "Marital Status Change";
	
    /**
     *  Constant for a type of change, this is used both for the 'changeType' field
     *  in the Change Request table as well as many places through these objects.
     *  <b>NOTE:</b> A copy of these constants exists in the /CampusHR/formConfirm.jsp
     *  file, because these constants cannot be accessed from a JSP.
     */
    public static final String DEPENDENT_CHANGE = "Dependent Change";
	
    /**
     *  Constant for a type of change, this is used both for the 'changeType' field
     *  in the Change Request table as well as many places through these objects.
     *  <b>NOTE:</b> A copy of these constants exists in the /CampusHR/formConfirm.jsp
     *  file, because these constants cannot be accessed from a JSP.
     */
    public static final String JOB_CHANGE = "Job Change Request";
	
    /**
     *  Constant for a type of change, this is used both for the 'changeType' field
     *  in the Change Request table as well as many places through these objects.
     *  <b>NOTE:</b> A copy of these constants exists in the /CampusHR/formConfirm.jsp
     *  file, because these constants cannot be accessed from a JSP.
     */
    public static final String LEAVE_OF_ABSENCE = "Leave of Absence";
	
    /**
     *  Constant for a type of change, this is used both for the 'changeType' field
     *  in the Change Request table as well as many places through these objects.
     *  <b>NOTE:</b> A copy of these constants exists in the /CampusHR/formConfirm.jsp
     *  file, because these constants cannot be accessed from a JSP.
     */
    public static final String RESIGNATION = "Resignation";

    /**
     *  The constant used for an HR regional director.  A compare is done with this 
     *  constant and the value of the 'role' column in the Staff table.
     */
    public static final String HR_REGIONAL_DIR = "HRRD";
	
    /**
     *  The constant used for an HR national director.  A compare is done with this 
     *  constant and the value of the 'role' column in the Staff table.
     */
    public static final String HR_NATIONAL_DIR = "HRND";

    public static final String HR_NON_CAMPUS = "HRNC";


    public String getChangeRequestID(){
            return changeRequestID;
        }

    public void setChangeRequestID(String changeRequestID){
            this.changeRequestID = changeRequestID;
        }

    public Staff getUpdateStaff() {
		return this.updateStaff;
    }
    public void setUpdateStaff(Staff staff) {
		this.updateStaff = staff;
    }

    public void assocUpdateStaff(Staff staff) {
		this.updateStaff = staff;
    }

	/**
	 * @primary-key
	 */
    private String changeRequestID = new String();

    /**
     * @shapeType AssociationLink 
     * @clientCardinality 0..1
     * @clientRole updateStaff
     * @supplierCardinality 0..n
     * @supplierRole updateRequest
     * @label hasChangeRequest
     */
     private Staff updateStaff;
}
