/* Generated by Together */

package org.alt60m.ministry.model;
import java.util.*;

/**
 * @persistent 
 * @table ministry_statistic
 * @key-generator UUID
 * @cache-type none
 * @access shared
 */
public class Statistic {

	/**
	 * @primary-key
	 */
    private String statisticID = new String();

    private Date periodBegin;
    private Date periodEnd;
    private int exposures;
    private int decisions;
    private int attendedLastConf;
    private int invldNewBlvrs;
    private int invldStudents;
    private int invldFreshmen;
    private int invldSophomores;
    private int invldJuniors;
    private int invldSeniors;
    private int invldGrads;
    private int volunteers;
    private int staff;
    private int nonStaffStint;
    private int staffStint;

	public Date getPeriodBegin() {
		return periodBegin; 
	}
	public void setPeriodBegin(Date periodBegin) {
	    if (periodBegin != null) {
		Calendar cin = Calendar.getInstance();
		Calendar cout = Calendar.getInstance();
		cin.setTime(periodBegin);
		cout.clear();
		cout.set(cin.get(Calendar.YEAR), cin.get(Calendar.MONTH), cin.get(Calendar.DATE));
		this.periodBegin = cout.getTime();
	    } else {
		this.periodBegin = periodBegin;
	    }	    
	}
	public Date getPeriodEnd() {
		return periodEnd; 
	}
	public void setPeriodEnd(Date periodEnd) {
	    if (periodEnd != null) {
		Calendar cin = Calendar.getInstance();
		Calendar cout = Calendar.getInstance();
		cin.setTime(periodEnd);
		cout.clear();
		cout.set(cin.get(Calendar.YEAR), cin.get(Calendar.MONTH), cin.get(Calendar.DATE));
		this.periodEnd = cout.getTime();
	    } else {
		this.periodEnd = periodEnd;
	    }	    
	}
	public int getExposures() {
		return exposures; 
	}
	public void setExposures(int exposures) {
		this.exposures = exposures; 
	}
	public int getDecisions() {
		return decisions; 
	}
	public void setDecisions(int decisions) {
		this.decisions = decisions; 
	}
	public int getAttendedLastConf() {
		return attendedLastConf; 
	}
	public void setAttendedLastConf(int attendedLastConf) {
		this.attendedLastConf = attendedLastConf; 
	}
	public int getInvldNewBlvrs() {
		return invldNewBlvrs; 
	}
	public void setInvldNewBlvrs(int invldNewBlvrs) {
		this.invldNewBlvrs = invldNewBlvrs; 
	}
	public int getInvldStudents() {
		return invldStudents; 
	}
	public void setInvldStudents(int invldStudents) {
		this.invldStudents = invldStudents; 
	}
	public int getInvldFreshmen() {
		return invldFreshmen; 
	}
	public void setInvldFreshmen(int invldFreshmen) {
		this.invldFreshmen = invldFreshmen; 
	}
	public int getInvldSophomores() {
		return invldSophomores; 
	}
	public void setInvldSophomores(int invldSophomores) {
		this.invldSophomores = invldSophomores; 
	}
	public int getInvldJuniors() {
		return invldJuniors; 
	}
	public void setInvldJuniors(int invldJuniors) {
		this.invldJuniors = invldJuniors; 
	}
	public int getInvldSeniors() {
		return invldSeniors; 
	}
	public void setInvldSeniors(int invldSeniors) {
		this.invldSeniors = invldSeniors; 
	}
	public int getInvldGrads() {
		return invldGrads; 
	}
	public void setInvldGrads(int invldGrads) {
		this.invldGrads = invldGrads; 
	}
	public int getVolunteers() {
		return volunteers; 
	}
	public void setVolunteers(int volunteers) {
		this.volunteers = volunteers; 
	}
	public int getStaff() {
		return staff; 
	}
	public void setStaff(int staff) {
		this.staff = staff; 
	}
	public int getNonStaffStint() {
		return nonStaffStint; 
	}
	public void setNonStaffStint(int nonStaffStint) {
		this.nonStaffStint = nonStaffStint; 
	}
	public int getStaffStint() {
		return staffStint; 
	}
	public void setStaffStint(int staffStint) {
		this.staffStint = staffStint; 
	}

    public String getStatisticID(){
            return statisticID;
        }

    public void setStatisticID(String statisticID){
            this.statisticID = statisticID;
        }

    public Activity getActivity(){
            return activity;
        }

    public void setActivity(Activity activity){
            this.activity = activity;
        }

    /**
    * @sql-name fk_Activity
    */
    private Activity activity;
}
