/* Generated by Together */

package org.alt60m.ministry.model;

import java.util.*;
//import java.util.Date;

/**
 * @persistent 
 * @table ministry_targetarea
 * @key-generator UUID
 * @cache-type none
 * @access shared
 */
public class TargetArea {
	/**
	 * @primary-key
	 */
	private String targetAreaID = new String();
    private String name = new String();
    private String address1 = new String();
    private String address2 = new String();
    private String city = new String();
    private String state = new String();
    private String zip = new String();
    private String country = new String();
    private String phone = new String();
    private String fax = new String();
    private String email = new String();
    private String url = new String();
    private String abbrv = new String();
    private String fice = new String();
    private String population = new String();
    private String note = new String();
    private String altName = new String();

    /**
    * @sql-type char[TF]
    */
    private boolean isSecure;
    private String region = new String();
    private String mpta = new String();
    private String urlToLogo = new String();
    private String enrollment = new String();
    private String monthSchoolStarts = new String();
    private String monthSchoolStops = new String();
    /**
    * @sql-type char[TF]
    */
    private boolean isSemester;
    private String aoaPriority = new String();
    private String aoa = new String();
    private String ciaUrl = new String();
    private String infoUrl = new String();
    /**
    * @sql-type char[TF]
    */
    private boolean isApproved;

	public String getName() {
		return name; 
	}
	public void setName(String name) {
		this.name = name; 
	}
	public String getAddress1() {
		return address1; 
	}
	public void setAddress1(String address1) {
		this.address1 = address1; 
	}
	public String getAddress2() {
		return address2; 
	}
	public void setAddress2(String address2) {
		this.address2 = address2; 
	}
	public String getCity() {
		return city; 
	}
	public void setCity(String city) {
		this.city = city; 
	}
	public String getState() {
		return state; 
	}
	public void setState(String state) {
		this.state = state; 
	}
	public String getZip() {
		return zip; 
	}
	public void setZip(String zip) {
		this.zip = zip; 
	}
	public String getCountry() {
		return country; 
	}
	public void setCountry(String country) {
		this.country = country; 
	}
	public String getPhone() {
		return phone; 
	}
	public void setPhone(String phone) {
		this.phone = phone; 
	}
	public String getFax() {
		return fax; 
	}
	public void setFax(String fax) {
		this.fax = fax; 
	}
	public String getEmail() {
		return email; 
	}
	public void setEmail(String email) {
		this.email = email; 
	}
	public String getUrl() {
		return url; 
	}
	public void setUrl(String url) {
		this.url = url; 
	}
	public String getAbbrv() {
		return abbrv; 
	}
	public void setAbbrv(String abbrv) {
		this.abbrv = abbrv; 
	}
	public String getFice() {
		return fice; 
	}
	public void setFice(String fice) {
		this.fice = fice; 
	}
	public String getPopulation() {
		return population; 
	}
	public void setPopulation(String population) {
		this.population = population; 
	}
	public String getNote() {
		return note; 
	}
	public void setNote(String note) {
		this.note = note; 
	}
	public String getAltName() {
		return altName; 
	}
	public void setAltName(String altName) {
		this.altName = altName; 
	}
	public boolean getIsSecure() {
		return isSecure; 
	}
	public void setIsSecure(boolean isSecure) {
		this.isSecure = isSecure; 
	}
	public String getRegion() {
		return region; 
	}
	public void setRegion(String region) {
		this.region = region; 
	}
	public String getMpta() {
		return mpta; 
	}
	public void setMpta(String mpta) {
		this.mpta = mpta; 
	}
	public String getUrlToLogo() {
		return urlToLogo; 
	}
	public void setUrlToLogo(String urlToLogo) {
		this.urlToLogo = urlToLogo; 
	}
	public String getEnrollment() {
		return enrollment; 
	}
	public void setEnrollment(String enrollment) {
		this.enrollment = enrollment; 
	}
	public String getMonthSchoolStarts() {
		return monthSchoolStarts; 
	}
	public void setMonthSchoolStarts(String monthSchoolStarts) {
		this.monthSchoolStarts = monthSchoolStarts; 
	}
	public String getMonthSchoolStops() {
		return monthSchoolStops; 
	}
	public void setMonthSchoolStops(String monthSchoolStops) {
		this.monthSchoolStops = monthSchoolStops; 
	}
	public boolean getIsSemester() {
		return isSemester; 
	}
	public void setIsSemester(boolean isSemester) {
		this.isSemester = isSemester; 
	}
	public String getAoaPriority() {
		return aoaPriority; 
	}
	public void setAoaPriority(String aoaPriority) {
		this.aoaPriority = aoaPriority; 
	}
	public String getAoa() {
		return aoa; 
	}
	public void setAoa(String aoa) {
		this.aoa = aoa; 
	}
	public String getCiaUrl() {
		return ciaUrl; 
	}
	public void setCiaUrl(String ciaUrl) {
		this.ciaUrl = ciaUrl; 
	}
	public String getInfoUrl() {
		return infoUrl; 
	}
	public void setInfoUrl(String infoUrl) {
		this.infoUrl = infoUrl; 
	}
	public Collection getActivities() {
		return activities; 
	}
	public void setActivities(Collection activities) {
		this.activities = activities; 
	}
    public void assocActivity(Activity activity) {
		if(!this.activities.contains(activity)) {
			this.activities.add(activity);
        }
        activity.setTargetArea(this);
    }
    public void dissocActivity(Activity activity) {
		this.activities.remove(activity);
        activity.setTargetArea(null);
    }

    public String getTargetAreaID(){
            return targetAreaID;
        }

    public void setTargetAreaID(String targetAreaID){
            this.targetAreaID = targetAreaID;
        }

    public boolean getIsApproved(){
            return isApproved;
        }

    public void setIsApproved(boolean isApproved){
            this.isApproved = isApproved;
        }

     public Collection getOtherMinistries(){
             return otherMinistries;
         }

     public void setOtherMinistries(Collection otherMinistries){
             this.otherMinistries = otherMinistries;
         }

    /**
     * @field-type org.alt60m.ministry.model.NonCccMin
     * @many-table ministry_assoc_otherministries
     */
     private Collection otherMinistries = new Vector();

    /**
     * @associates <{Activity}>
     * @clientCardinality 0..1
     * @supplierCardinality 0..*
     * @label activities
     * @undirected
     * @field-type org.alt60m.ministry.model.Activity
     * @many-key fk_targetAreaID
     */
    private Collection activities = new Vector();
}
